package ff6

import (
	"pixel-remastered-save-editor/models"
)

var (
	Bestiary = []models.NameValue{
		models.NewValueName(1, "Guard"),
		models.NewValueName(2, "Imperial Soldier"),
		models.NewValueName(3, "Templar"),
		models.NewValueName(4, "Ninja"),
		models.NewValueName(5, "Samurai"),
		models.NewValueName(6, "Borghese"),
		models.NewValueName(7, "Magna Roader"),
		models.NewValueName(8, "Yojimbo"),
		models.NewValueName(9, "Cloud"),
		models.NewValueName(10, "Misty"),
		models.NewValueName(11, "Al Jabr"),
		models.NewValueName(12, "Zaghrem"),
		models.NewValueName(13, "Apocrypha"),
		models.NewValueName(14, "Dark Force"),
		models.NewValueName(15, "Angel Whisper"),
		models.NewValueName(16, "Oversoul"),
		models.NewValueName(17, "Skeletal Horror"),
		models.NewValueName(18, "Commander"),
		models.NewValueName(19, "Mu"),
		models.NewValueName(20, "Wererat"),
		models.NewValueName(21, "Mugbear"),
		models.NewValueName(22, "Belmodar"),
		models.NewValueName(23, "Muud Suud"),
		models.NewValueName(24, "Leaf Bunny"),
		models.NewValueName(25, "Stray Cat"),
		models.NewValueName(26, "Silver Lobo"),
		models.NewValueName(27, "Doberman"),
		models.NewValueName(28, "Megalodoth"),
		models.NewValueName(29, "Fidor"),
		models.NewValueName(30, "Briareus"),
		models.NewValueName(31, "Suriander"),
		models.NewValueName(32, "Chimera"),
		models.NewValueName(33, "Behemoth"),
		models.NewValueName(34, "Fafnir"),
		models.NewValueName(35, "Lesser Lopros"),
		models.NewValueName(36, "Fossil Dragon"),
		models.NewValueName(37, "Holy Dragon"),
		models.NewValueName(38, "Fiend Dragon"),
		models.NewValueName(39, "Brachiosaur"),
		models.NewValueName(40, "Tyrannosaur"),
		models.NewValueName(41, "Darkwind"),
		models.NewValueName(42, "Aepyornis"),
		models.NewValueName(43, "Vulture"),
		models.NewValueName(44, "Vasegiatta"),
		models.NewValueName(45, "Zokka"),
		models.NewValueName(46, "Trapper"),
		models.NewValueName(47, "Hornet"),
		models.NewValueName(48, "Nettlehopper"),
		models.NewValueName(49, "Delta Beetle"),
		models.NewValueName(50, "Killer Mantis"),
		models.NewValueName(51, "Trillium"),
		models.NewValueName(52, "Rafflesia"),
		models.NewValueName(53, "Tumbleweed"),
		models.NewValueName(54, "Vampire Thorn"),
		models.NewValueName(55, "Cartagra"),
		models.NewValueName(56, "Siegfried"),
		models.NewValueName(57, "Nautiloid"),
		models.NewValueName(58, "Exocite"),
		models.NewValueName(59, "Anguiform"),
		models.NewValueName(60, "Leap Frog"),
		models.NewValueName(61, "Lizard"),
		models.NewValueName(62, "Litwor Chicken"),
		models.NewValueName(63, "Slagworm"),
		models.NewValueName(64, "Hell's Rider"),
		models.NewValueName(65, "Typhon"),
		models.NewValueName(66, "Onion Knight"),
		models.NewValueName(67, "Magitek Armor"),
		models.NewValueName(68, "Sky Armor"),
		models.NewValueName(69, "Satellite"),
		models.NewValueName(70, "Armored Weapon"),
		models.NewValueName(71, "Spritzer"),
		models.NewValueName(72, "Flan"),
		models.NewValueName(73, "Outcast"),
		models.NewValueName(74, "Humpty"),
		models.NewValueName(75, "Brainpan"),
		models.NewValueName(76, "Cruller"),
		models.NewValueName(77, "Cactuar"),
		models.NewValueName(78, "Bandit"),
		models.NewValueName(79, "Harvester"),
		models.NewValueName(80, "Bomb"),
		models.NewValueName(81, "Still Life"),
		models.NewValueName(82, "Lunatys"),
		models.NewValueName(83, "Veil Dancer"),
		models.NewValueName(84, "Hill Gigas"),
		models.NewValueName(85, "Tonberry"),
		models.NewValueName(86, "Magic Urn"),
		models.NewValueName(87, "Mover"),
		models.NewValueName(88, "Figaro Lizard"),
		models.NewValueName(89, "Devoahan"),
		models.NewValueName(90, "Aspiran"),
		models.NewValueName(91, "Ghost"),
		models.NewValueName(92, "Crawler"),
		models.NewValueName(93, "Sand Ray"),
		models.NewValueName(94, "Alacran"),
		models.NewValueName(95, "Actinian"),
		models.NewValueName(96, "Sandhorse"),
		models.NewValueName(97, "Darkside"),
		models.NewValueName(98, "Malboro"),
		models.NewValueName(99, "Urok"),
		models.NewValueName(100, "Foper"),
		models.NewValueName(101, "Guard Leader"),
		models.NewValueName(102, "Corporal"),
		models.NewValueName(103, "General"),
		models.NewValueName(104, "Covert"),
		models.NewValueName(105, "Kamui"),
		models.NewValueName(106, "Warlock"),
		models.NewValueName(107, "Cherry"),
		models.NewValueName(108, "Joker"),
		models.NewValueName(109, "Iron Fist"),
		models.NewValueName(110, "Devil"),
		models.NewValueName(111, "Provoker"),
		models.NewValueName(112, "Cloudwraith"),
		models.NewValueName(113, "Mahadeva"),
		models.NewValueName(114, "Vector Hound"),
		models.NewValueName(115, "Peeper"),
		models.NewValueName(116, "Stunner"),
		models.NewValueName(117, "Sorath"),
		models.NewValueName(118, "Destroyer"),
		models.NewValueName(119, "Chippirabbit"),
		models.NewValueName(120, "Coeurl Cat"),
		models.NewValueName(121, "Bloodfang"),
		models.NewValueName(122, "Hunting Hound"),
		models.NewValueName(123, "Gorgias"),
		models.NewValueName(124, "Don"),
		models.NewValueName(125, "Murussu"),
		models.NewValueName(126, "Wartpuck"),
		models.NewValueName(127, "Gorgimera"),
		models.NewValueName(128, "Behemoth King"),
		models.NewValueName(129, "Vector Lythos"),
		models.NewValueName(130, "Wyvern"),
		models.NewValueName(131, "Zombie Dragon"),
		models.NewValueName(132, "Dragon"),
		models.NewValueName(133, "Primeval Dragon"),
		models.NewValueName(134, "Weredragon"),
		models.NewValueName(135, "Cirpius"),
		models.NewValueName(136, "Sprinter"),
		models.NewValueName(137, "Lenergia"),
		models.NewValueName(138, "Marchosias"),
		models.NewValueName(139, "Gloomwind"),
		models.NewValueName(140, "Dropper"),
		models.NewValueName(141, "Rock Wasp"),
		models.NewValueName(142, "Grasswyrm"),
		models.NewValueName(143, "Luridan"),
		models.NewValueName(144, "Twinscythe"),
		models.NewValueName(145, "Paraladia"),
		models.NewValueName(146, "Exoray"),
		models.NewValueName(147, "Crusher"),
		models.NewValueName(148, "Ouroboros"),
		models.NewValueName(149, "Acrophies"),
		models.NewValueName(150, "Schmidt"),
		models.NewValueName(151, "Devourer"),
		models.NewValueName(152, "Cancer"),
		models.NewValueName(153, "Gigantoad"),
		models.NewValueName(154, "Basilisk"),
		models.NewValueName(155, "Medusa Chicken"),
		models.NewValueName(156, "Landworm"),
		models.NewValueName(157, "Test Rider"),
		models.NewValueName(158, "Pluto Armor"),
		models.NewValueName(159, "Onion Dasher"),
		models.NewValueName(160, "Heavy Armor"),
		models.NewValueName(161, "Chaser"),
		models.NewValueName(162, "Gamma"),
		models.NewValueName(163, "Poplium"),
		models.NewValueName(164, "Intangir"),
		models.NewValueName(165, "Misfit"),
		models.NewValueName(166, "Creature"),
		models.NewValueName(167, "Enuo"),
		models.NewValueName(168, "Deepeye"),
		models.NewValueName(169, "Unseelie"),
		models.NewValueName(170, "Neck Hunter"),
		models.NewValueName(171, "Grenade"),
		models.NewValueName(172, "Alluring Rider"),
		models.NewValueName(173, "Pandora"),
		models.NewValueName(174, "Blade Dancer"),
		models.NewValueName(175, "Gigantos"),
		models.NewValueName(176, "Magna Roader"),
		models.NewValueName(177, "Lycaon"),
		models.NewValueName(178, "Parasite"),
		models.NewValueName(179, "Land Ray"),
		models.NewValueName(180, "Antares"),
		models.NewValueName(181, "Anemone"),
		models.NewValueName(182, "Moonform"),
		models.NewValueName(183, "Specter"),
		models.NewValueName(184, "Great Malboro"),
		models.NewValueName(185, "Bonnacon"),
		models.NewValueName(186, "Oceanus"),
		models.NewValueName(187, "Living Dead"),
		models.NewValueName(188, "Death Warden"),
		models.NewValueName(189, "Face"),
		models.NewValueName(190, "Outsider"),
		models.NewValueName(191, "Coco"),
		models.NewValueName(192, "Zeveak"),
		models.NewValueName(193, "Nightwalker"),
		models.NewValueName(194, "Demon Knight"),
		models.NewValueName(195, "Imperial Elite"),
		models.NewValueName(196, "Desert Hare"),
		models.NewValueName(197, "Wizard"),
		models.NewValueName(198, "Devil Fist"),
		models.NewValueName(199, "Illuyankas"),
		models.NewValueName(200, "Sergeant"),
		models.NewValueName(201, "Aspidochelon"),
		models.NewValueName(202, "Knotty"),
		models.NewValueName(203, "Luna Wolf"),
		models.NewValueName(204, "Belzecue"),
		models.NewValueName(205, "Caladrius"),
		models.NewValueName(206, "Tzakmaqiel"),
		models.NewValueName(207, "Lukhavi"),
		models.NewValueName(208, "Eukaryote"),
		models.NewValueName(209, "Land Grillon"),
		models.NewValueName(210, "Goetia"),
		models.NewValueName(211, "Greater Mantis"),
		models.NewValueName(212, "Bogy"),
		models.NewValueName(213, "Purusa"),
		models.NewValueName(214, "Black Dragon"),
		models.NewValueName(215, "Adamankary"),
		models.NewValueName(216, "Dante"),
		models.NewValueName(217, "Platinum Dragon"),
		models.NewValueName(218, "Duel Armor"),
		models.NewValueName(219, "Psychos"),
		models.NewValueName(220, "Mousse"),
		models.NewValueName(221, "Shambling Corpse"),
		models.NewValueName(222, "Punisher"),
		models.NewValueName(223, "Balloon"),
		models.NewValueName(224, "Gobbledygook"),
		models.NewValueName(225, "Great Behemoth"),
		models.NewValueName(226, "Scorpion"),
		models.NewValueName(227, "Chaos Dragon"),
		models.NewValueName(228, "Spitfire"),
		models.NewValueName(229, "Vector Chimera"),
		models.NewValueName(230, "Lich"),
		models.NewValueName(231, "Rukh"),
		models.NewValueName(232, "Magna Roader"),
		models.NewValueName(233, "Bug"),
		models.NewValueName(234, "Seaflower"),
		models.NewValueName(235, "Fortis"),
		models.NewValueName(236, "Venobennu"),
		models.NewValueName(237, "Galypdes"),
		models.NewValueName(238, "Junk"),
		models.NewValueName(239, "Mandrake"),
		models.NewValueName(240, "Valeor"),
		models.NewValueName(241, "Amduscias"),
		models.NewValueName(242, "Necromancer"),
		models.NewValueName(243, "Glasya Labolas"),
		models.NewValueName(244, "Magna Roader"),
		models.NewValueName(245, "Wild Rat"),
		models.NewValueName(246, "Gold Bear"),
		models.NewValueName(247, "InnoSent"),
		models.NewValueName(248, "Clymenus"),
		models.NewValueName(249, "Garm"),
		models.NewValueName(250, "Daedalus"),
		models.NewValueName(251, "Baalzephon"),
		models.NewValueName(252, "Ahriman"),
		models.NewValueName(253, "Death Machine"),
		models.NewValueName(254, "Metal Hitman"),
		models.NewValueName(255, "Io"),
		models.NewValueName(256, "Tonberries"),
		models.NewValueName(257, "Ymir"),
		models.NewValueName(258, "Angler Whelk"),
		models.NewValueName(259, "Mega Armor"),
		models.NewValueName(260, "Vargas"),
		models.NewValueName(261, "Tunnel Armor"),
		models.NewValueName(262, "Prometheus"),
		models.NewValueName(263, "Phantom Train"),
		models.NewValueName(264, "Dadaluma"),
		models.NewValueName(265, "Shiva"),
		models.NewValueName(266, "Ifrit"),
		models.NewValueName(267, "Number 024"),
		models.NewValueName(268, "Number 128"),
		models.NewValueName(269, "Inferno"),
		models.NewValueName(270, "Crane"),
		models.NewValueName(271, "Crane"),
		models.NewValueName(272, "Yeti"),
		models.NewValueName(273, "Yeti"),
		models.NewValueName(274, "Guardian"),
		models.NewValueName(275, "Guardian"),
		models.NewValueName(276, "Air Force"),
		models.NewValueName(277, "Frozen Esper"),
		models.NewValueName(278, "Frozen Esper"),
		models.NewValueName(279, "Flame Eater"),
		models.NewValueName(280, "Ultima Weapon"),
		models.NewValueName(281, "Nelapa"),
		models.NewValueName(282, "Behemoth King"),
		models.NewValueName(283, "Kefka"),
		models.NewValueName(284, "Tentacle"),
		models.NewValueName(285, "Dullahan"),
		models.NewValueName(286, "Deathgaze"),
		models.NewValueName(287, "Chadarnook"),
		models.NewValueName(288, "Curlax"),
		models.NewValueName(289, "Laragorn"),
		models.NewValueName(290, "Moebius"),
		models.NewValueName(291, "Wrexsoul"),
		models.NewValueName(292, "Hidon"),
		models.NewValueName(293, "Samurai Soul"),
		models.NewValueName(294, "Level 30 Magic"),
		models.NewValueName(295, "Erebus"),
		models.NewValueName(296, "Fiend"),
		models.NewValueName(297, "Goddess"),
		models.NewValueName(298, "Demon"),
		models.NewValueName(299, "Kefka"),
		models.NewValueName(300, "Level 40 Magic"),
		models.NewValueName(301, "Ultros"),
		models.NewValueName(302, "Ultros"),
		models.NewValueName(303, "Ultros"),
		models.NewValueName(304, "Typhon"),
		models.NewValueName(305, "Level 20 Magic"),
		models.NewValueName(306, "Siegfried"),
		models.NewValueName(307, "Level 10 Magic"),
		models.NewValueName(308, "Level 50 Magic"),
		models.NewValueName(309, "Ymir"),
		models.NewValueName(310, "Angler Whelk"),
		models.NewValueName(313, "Master Tonberry"),
		models.NewValueName(314, "Level 60 Magic"),
		models.NewValueName(315, "Merchant"),
		models.NewValueName(316, "Birthday Suit"),
		models.NewValueName(317, "Tentacle"),
		models.NewValueName(318, "Tentacle"),
		models.NewValueName(319, "Tentacle"),
		models.NewValueName(320, "Right Blade"),
		models.NewValueName(321, "Left Blade"),
		models.NewValueName(322, "Rahu"),
		models.NewValueName(323, "Ketu"),
		models.NewValueName(324, "Level 70 Magic"),
		models.NewValueName(325, "Valigarmanda"),
		models.NewValueName(326, "Laser Gun"),
		models.NewValueName(327, "Bit"),
		models.NewValueName(328, "Missile Bay"),
		models.NewValueName(329, "Chadarnook"),
		models.NewValueName(330, "Ice Dragon"),
		models.NewValueName(331, "Kefka"),
		models.NewValueName(332, "Storm Dragon"),
		models.NewValueName(333, "Earth Dragon"),
		models.NewValueName(334, "Ipooh"),
		models.NewValueName(335, "Captain"),
		models.NewValueName(336, "Soldier"),
		models.NewValueName(337, "Gold Dragon"),
		models.NewValueName(338, "Skull Dragon"),
		models.NewValueName(339, "Blue Dragon"),
		models.NewValueName(340, "Red Dragon"),
		models.NewValueName(341, "Opinicus Fish"),
		models.NewValueName(342, "Rhizopas"),
		models.NewValueName(343, "Apparition"),
		models.NewValueName(344, "Statue of the Gods A"),
		models.NewValueName(345, "Statue of the Gods B"),
		models.NewValueName(346, "Statue of the Gods C"),
		models.NewValueName(347, "Statue of the Gods D"),
		models.NewValueName(348, "Statue of the Gods E"),
		models.NewValueName(349, "Statue of the Gods F"),
		models.NewValueName(350, "Statue of the Gods G"),
		models.NewValueName(351, "Statue of the Gods H"),
		models.NewValueName(352, "Statue of the Gods I"),
		models.NewValueName(353, "Erebus"),
		models.NewValueName(354, "Erebus"),
		models.NewValueName(355, "Erebus"),
		models.NewValueName(356, "Level 80 Magic"),
		models.NewValueName(357, "Level 90 Magic"),
		models.NewValueName(358, "Proto Armor"),
		models.NewValueName(359, "Magic Master"),
		models.NewValueName(360, "Soul Saver"),
		models.NewValueName(361, "Ultros"),
		models.NewValueName(362, "Naude"),
		models.NewValueName(363, "Humbaba"),
		models.NewValueName(364, "Humbaba"),
		models.NewValueName(365, "Humbaba"),
		models.NewValueName(366, "Humbaba"),
		models.NewValueName(368, "Kefka"),
		models.NewValueName(370, "Zone Eater"),
		models.NewValueName(372, "Kefka"),
		models.NewValueName(373, "Kefka"),
		models.NewValueName(374, "Cadet"),
		models.NewValueName(375, "Officer"),
		models.NewValueName(378, "Imperial Soldier"),
		models.NewValueName(382, "Ultima Buster"),
		models.NewValueName(408, "Red Dragon"),
		models.NewValueName(409, "Blue Dragon"),
		models.NewValueName(410, "Gold Dragon"),
		models.NewValueName(411, "Skull Dragon"),
		models.NewValueName(412, "Storm Dragon"),
		models.NewValueName(413, "Earth Dragon"),
		models.NewValueName(414, "Holy Dragon"),
		models.NewValueName(415, "Ice Dragon"),
		models.NewValueName(424, "Statue of the Gods A"),
		models.NewValueName(425, "Statue of the Gods B"),
		models.NewValueName(426, "Statue of the Gods C"),
		models.NewValueName(500, "Typhon"),
		models.NewValueName(501, "Wartpuck"),
		models.NewValueName(502, "Test Rider"),
		models.NewValueName(503, "Shambling Corpse"),
		models.NewValueName(504, "Baalzephon"),
		models.NewValueName(505, "Great Malboro"),
		models.NewValueName(506, "Gamma"),
		models.NewValueName(507, "Muud Suud"),
		models.NewValueName(508, "Armored Weapon"),
		models.NewValueName(509, "Enuo"),
		models.NewValueName(510, "Glasya Labolas"),
		models.NewValueName(511, "Outsider"),
		models.NewValueName(512, "Aspidochelon"),
		models.NewValueName(513, "Behemoth King"),
		models.NewValueName(514, "Covert"),
		models.NewValueName(515, "Daedalus"),
		models.NewValueName(516, "Great Behemoth"),
		models.NewValueName(517, "Death Machine"),
		models.NewValueName(518, "Landworm"),
		models.NewValueName(519, "Weredragon"),
		models.NewValueName(520, "Face"),
		models.NewValueName(521, "Shadow"),
		models.NewValueName(522, "Gorgimera"),
		models.NewValueName(523, "Galypdes"),
		models.NewValueName(524, "Tonberry"),
		models.NewValueName(525, "Chaos Dragon"),
		models.NewValueName(526, "Clymenus"),
		models.NewValueName(527, "Tumbleweed"),
		models.NewValueName(528, "Greater Mantis"),
		models.NewValueName(529, "Metal Hitman"),
		models.NewValueName(530, "InnoSent"),
		models.NewValueName(531, "Yojimbo"),
		models.NewValueName(532, "Demon Knight"),
		models.NewValueName(533, "Dark Force"),
		models.NewValueName(534, "Duel Armor"),
		models.NewValueName(535, "Slagworm"),
		models.NewValueName(536, "Fortis"),
		models.NewValueName(537, "Brachiosaur"),
		models.NewValueName(538, "Vector Chimera"),
		models.NewValueName(539, "Vector Lythos"),
		models.NewValueName(540, "Ahriman"),
		models.NewValueName(541, "Cherry"),
		models.NewValueName(542, "Primeval Dragon"),
		models.NewValueName(543, "Amduscias"),
		models.NewValueName(544, "Vasegiatta"),
		models.NewValueName(545, "Tyrannosaur"),
		models.NewValueName(546, "Fiend Dragon"),
		models.NewValueName(547, "Cactuar"),
		models.NewValueName(548, "Siegfried"),
		models.NewValueName(549, "Gau"),
		models.NewValueName(550, "Gau"),
		models.NewValueName(551, "Chaser"),
		models.NewValueName(552, "Ifrit"),
		models.NewValueName(553, "Outsider"),
		models.NewValueName(554, "Outsider"),
		models.NewValueName(555, "Outsider"),
		models.NewValueName(556, "Demon Knight"),
		models.NewValueName(557, "Demon Knight"),
		models.NewValueName(558, "Aspidochelon"),
		models.NewValueName(559, "Aspidochelon"),
		models.NewValueName(560, "Aspidochelon"),
		models.NewValueName(561, "Aspidochelon"),
		models.NewValueName(562, "Aspidochelon"),
		models.NewValueName(563, "Aspidochelon"),
		models.NewValueName(564, "Covert"),
		models.NewValueName(565, "Covert"),
		models.NewValueName(566, "Weredragon"),
		models.NewValueName(567, "Weredragon"),
		models.NewValueName(568, "Weredragon"),
		models.NewValueName(569, "Weredragon"),
		models.NewValueName(570, "Weredragon"),
		models.NewValueName(571, "Weredragon"),
		models.NewValueName(572, "Gamma"),
		models.NewValueName(573, "Gamma"),
		models.NewValueName(574, "Behemoth King"),
		models.NewValueName(575, "Behemoth King"),
		models.NewValueName(576, "Glasya Labolas"),
		models.NewValueName(577, "Glasya Labolas"),
		models.NewValueName(578, "Glasya Labolas"),
		models.NewValueName(579, "Glasya Labolas"),
		models.NewValueName(580, "Glasya Labolas"),
		models.NewValueName(581, "Gorgimera"),
		models.NewValueName(582, "Gorgimera"),
		models.NewValueName(583, "Gorgimera"),
		models.NewValueName(584, "Gorgimera"),
		models.NewValueName(585, "Gorgimera"),
		models.NewValueName(586, "Cactuar"),
		models.NewValueName(587, "Daedalus"),
		models.NewValueName(588, "Death Machine"),
		models.NewValueName(589, "Death Machine"),
		models.NewValueName(590, "Typhon"),
		models.NewValueName(591, "Typhon"),
		models.NewValueName(592, "Test Rider"),
		models.NewValueName(593, "Test Rider"),
		models.NewValueName(594, "Test Rider"),
		models.NewValueName(595, "Test Rider"),
		models.NewValueName(596, "Test Rider"),
		models.NewValueName(597, "Tonberry"),
		models.NewValueName(598, "Tonberry"),
		models.NewValueName(599, "Dark Force"),
		models.NewValueName(600, "Dark Force"),
		models.NewValueName(601, "Vector Chimera"),
		models.NewValueName(602, "Vector Chimera"),
		models.NewValueName(603, "Vector Chimera"),
		models.NewValueName(604, "Muud Suud"),
		models.NewValueName(605, "Muud Suud"),
		models.NewValueName(606, "Muud Suud"),
		models.NewValueName(607, "Great Malboro"),
		models.NewValueName(608, "Great Malboro"),
		models.NewValueName(609, "Yojimbo"),
		models.NewValueName(610, "Yojimbo"),
	}
)
