package ff6

import (
	"pixel-remastered-save-editor/models"
)

var (
	Shields = []models.NameValue{
		models.NewValueName(201, "Buckler"),
		models.NewValueName(202, "Heavy Shield"),
		models.NewValueName(203, "Mythril Shield"),
		models.NewValueName(204, "Gold Shield"),
		models.NewValueName(205, "Aegis Shield"),
		models.NewValueName(206, "Diamond Shield"),
		models.NewValueName(207, "Flame Shield"),
		models.NewValueName(208, "Ice Shield"),
		models.NewValueName(209, "Thunder Shield"),
		models.NewValueName(210, "Crystal Shield"),
		models.NewValueName(211, "Genji Shield"),
		models.NewValueName(212, "Tortoise Shield"),
		models.NewValueName(213, "Cursed Shield"),
		models.NewValueName(214, "Paladin Shield"),
		models.NewValueName(215, "Force Shield"),
	}
	Helmets = []models.NameValue{
		models.NewValueName(199, "[Empty Head]"),
		models.NewValueName(216, "Leather Hat"),
		models.NewValueName(217, "Hairband"),
		models.NewValueName(218, "Plumed Hat"),
		models.NewValueName(219, "Beret"),
		models.NewValueName(220, "Magus Hat"),
		models.NewValueName(221, "Bandana"),
		models.NewValueName(222, "Iron Helmet"),
		models.NewValueName(223, "Priest's Miter"),
		models.NewValueName(224, "Bard's Hat"),
		models.NewValueName(225, "Green Beret"),
		models.NewValueName(226, "Head Band"),
		models.NewValueName(227, "Mythril Helm"),
		models.NewValueName(228, "Tiara"),
		models.NewValueName(229, "Gold Helmet"),
		models.NewValueName(230, "Tiger Mask"),
		models.NewValueName(231, "Red Hat"),
		models.NewValueName(232, "Mystery Veil"),
		models.NewValueName(233, "Circlet"),
		models.NewValueName(234, "Royal Crown"),
		models.NewValueName(235, "Diamond Helm"),
		models.NewValueName(236, "Black Hood"),
		models.NewValueName(237, "Crystal Helm"),
		models.NewValueName(238, "Oath Veil"),
		models.NewValueName(239, "Cat-Ear Hood"),
		models.NewValueName(240, "Genji Helmet"),
		models.NewValueName(241, "Thornlet"),
		models.NewValueName(242, "Saucer"),
	}
	Armors = []models.NameValue{
		models.NewValueName(198, "[Empty Body]"),
		models.NewValueName(244, "Leather Armor"),
		models.NewValueName(245, "Cotton Robe"),
		models.NewValueName(246, "Kenpo Gi"),
		models.NewValueName(247, "Iron Armor"),
		models.NewValueName(248, "Silk Robe"),
		models.NewValueName(249, "Mythril Vest"),
		models.NewValueName(250, "Ninja Gear"),
		models.NewValueName(251, "White Dress"),
		models.NewValueName(252, "Mythril Mail"),
		models.NewValueName(253, "Gaia Gear"),
		models.NewValueName(254, "Mirage Dress"),
		models.NewValueName(255, "Golden Armor"),
		models.NewValueName(256, "Power Sash"),
		models.NewValueName(257, "Luminous Robe"),
		models.NewValueName(258, "Diamond Vest"),
		models.NewValueName(259, "Red Jacket"),
		models.NewValueName(260, "Force Armor"),
		models.NewValueName(261, "Diamond Armor"),
		models.NewValueName(262, "Black Garb"),
		models.NewValueName(263, "Magus Rove"),
		models.NewValueName(264, "Crystal Mail"),
		models.NewValueName(265, "Regal Gown"),
		models.NewValueName(266, "Genji Armor"),
		models.NewValueName(267, "Reed Cloak"),
		models.NewValueName(268, "Minerva Bustier"),
		models.NewValueName(269, "Tabby Suit"),
		models.NewValueName(270, "Chocobo Suit"),
		models.NewValueName(271, "Moogle Suit"),
		models.NewValueName(272, "Nutkin Suit"),
		models.NewValueName(273, "Behemeth Suit"),
		models.NewValueName(274, "Snow Scarf"),
	}
	Hands = []models.NameValue{
		models.NewValueName(200, "[Empty Arms]"),
		models.NewValueName(275, "Silver Spectacles"),
		models.NewValueName(276, "Star Pendant"),
		models.NewValueName(277, "Peace Ring"),
		models.NewValueName(278, "Amulet"),
		models.NewValueName(279, "White Cape"),
		models.NewValueName(280, "Jewel Ring"),
		models.NewValueName(281, "Fairy Ring"),
		models.NewValueName(282, "Barrier Ring"),
		models.NewValueName(283, "Mythril Glove"),
		models.NewValueName(284, "Protect Ring"),
		models.NewValueName(285, "Hermes Sandals"),
		models.NewValueName(286, "Reflect Ring"),
		models.NewValueName(287, "Angel Wings"),
		models.NewValueName(288, "Angel Ring"),
		models.NewValueName(289, "Knight's Code"),
		models.NewValueName(290, "Dragoon Boots"),
		models.NewValueName(291, "Zephyr Cloak"),
		models.NewValueName(292, "Princess Ring"),
		models.NewValueName(293, "Cursed Ring"),
		models.NewValueName(294, "Earring"),
		models.NewValueName(295, "Gigas Glove"),
		models.NewValueName(296, "Blizzard Orb"),
		models.NewValueName(297, "Berserker Ring"),
		models.NewValueName(298, "Thief's Bracer"),
		models.NewValueName(299, "Guard Bracelet"),
		models.NewValueName(300, "Hero Ring"),
		models.NewValueName(301, "Ribbon"),
		models.NewValueName(302, "Muscle Belt"),
		models.NewValueName(303, "Crystal Orb"),
		models.NewValueName(304, "Gold Hairpin"),
		models.NewValueName(305, "Celestriad"),
		models.NewValueName(306, "Brigand's Glove"),
		models.NewValueName(307, "Gauntlet"),
		models.NewValueName(308, "Genji Glove"),
		models.NewValueName(309, "Hyper Wrist"),
		models.NewValueName(310, "Master's Scroll"),
		models.NewValueName(311, "Prayer Beads"),
		models.NewValueName(312, "Black Belt"),
		models.NewValueName(313, "Heiki's Jitte"),
		models.NewValueName(314, "Fake Mustache"),
		models.NewValueName(315, "Soul of Thamasa"),
		models.NewValueName(316, "Dragon Horn"),
		models.NewValueName(317, "Merit Award"),
		models.NewValueName(318, "Momento Ring"),
		models.NewValueName(319, "Safety Bit"),
		models.NewValueName(320, "Lich Ring"),
		models.NewValueName(321, "Molulu's Charm"),
		models.NewValueName(322, "Ward Bangle"),
		models.NewValueName(323, "Miracle Shoes"),
		models.NewValueName(324, "Alarm Gaurd"),
		models.NewValueName(325, "Gale Hairpin"),
		models.NewValueName(326, "Sniper Eye"),
		models.NewValueName(327, "Growth Egg"),
		models.NewValueName(328, "Tintinnabulum"),
		models.NewValueName(329, "Sprint Shoes"),
	}
)
