package ff6

import (
	"pixel-remastered-save-editor/models"
)

var (
	Maps = []models.NameValue{
		models.NewValueName(1, "Overworld (Balance)"),
		models.NewValueName(2, "Overworld (Ruin)"),
		models.NewValueName(3, "Narshe"),
		models.NewValueName(4, "Narshe"),
		models.NewValueName(5, "Narshe"),
		models.NewValueName(6, "Narshe"),
		models.NewValueName(7, "Narshe"),
		models.NewValueName(8, "Narshe"),
		models.NewValueName(9, "Narshe"),
		models.NewValueName(10, "Narshe"),
		models.NewValueName(11, "Narshe"),
		models.NewValueName(12, "Narshe"),
		models.NewValueName(13, "Narshe"),
		models.NewValueName(14, "Narshe"),
		models.NewValueName(15, "Narshe"),
		models.NewValueName(16, "Narshe"),
		models.NewValueName(17, "Narshe"),
		models.NewValueName(18, "Narshe"),
		models.NewValueName(19, "Narshe"),
		models.NewValueName(20, "Narshe"),
		models.NewValueName(21, "Figaro Castle"),
		models.NewValueName(22, "Figaro Castle"),
		models.NewValueName(23, "Figaro Castle"),
		models.NewValueName(24, "Figaro Castle"),
		models.NewValueName(25, "Figaro Castle"),
		models.NewValueName(26, "Figaro Castle"),
		models.NewValueName(27, "Figaro Castle"),
		models.NewValueName(28, "Figaro Castle"),
		models.NewValueName(29, "Figaro Castle"),
		models.NewValueName(30, "Figaro Castle"),
		models.NewValueName(31, "Figaro Castle"),
		models.NewValueName(32, "Figaro Castle"),
		models.NewValueName(33, "Figaro Castle"),
		models.NewValueName(34, "Figaro Castle"),
		models.NewValueName(35, "Figaro Castle"),
		models.NewValueName(36, "Duncan's Cabin"),
		models.NewValueName(37, "Duncan's Cabin"),
		models.NewValueName(38, "South Figaro"),
		models.NewValueName(39, "South Figaro"),
		models.NewValueName(40, "South Figaro"),
		models.NewValueName(41, "South Figaro"),
		models.NewValueName(42, "South Figaro"),
		models.NewValueName(43, "South Figaro"),
		models.NewValueName(44, "South Figaro"),
		models.NewValueName(45, "South Figaro"),
		models.NewValueName(46, "South Figaro"),
		models.NewValueName(47, "South Figaro"),
		models.NewValueName(48, "South Figaro"),
		models.NewValueName(49, "South Figaro"),
		models.NewValueName(50, "South Figaro"),
		models.NewValueName(51, "South Figaro"),
		models.NewValueName(52, "South Figaro"),
		models.NewValueName(53, "South Figaro"),
		models.NewValueName(54, "South Figaro"),
		models.NewValueName(55, "South Figaro"),
		models.NewValueName(56, "South Figaro"),
		models.NewValueName(57, "South Figaro"),
		models.NewValueName(58, "South Figaro"),
		models.NewValueName(59, "South Figaro"),
		models.NewValueName(60, "South Figaro"),
		models.NewValueName(61, "South Figaro"),
		models.NewValueName(62, "South Figaro"),
		models.NewValueName(63, "South Figaro"),
		models.NewValueName(64, "South Figaro"),
		models.NewValueName(65, "South Figaro"),
		models.NewValueName(66, "The Returners' Hideout"),
		models.NewValueName(67, "The Returners' Hideout"),
		models.NewValueName(68, "The Returners' Hideout"),
		models.NewValueName(69, "The Returners' Hideout"),
		models.NewValueName(70, "The Returners' Hideout"),
		models.NewValueName(71, "The Returners' Hideout"),
		models.NewValueName(72, "The Returners' Hideout"),
		models.NewValueName(73, "Cabin"),
		models.NewValueName(74, "Cabin"),
		models.NewValueName(75, "Doma Castle"),
		models.NewValueName(76, "Doma Castle"),
		models.NewValueName(77, "Doma Castle"),
		models.NewValueName(78, "Doma Castle"),
		models.NewValueName(79, "Doma Castle"),
		models.NewValueName(80, "Doma Castle"),
		models.NewValueName(81, "Doma Castle"),
		models.NewValueName(82, "Doma Castle"),
		models.NewValueName(83, "Doma Castle"),
		models.NewValueName(84, "Mobliz"),
		models.NewValueName(85, "Mobliz"),
		models.NewValueName(86, "Mobliz"),
		models.NewValueName(87, "Mobliz"),
		models.NewValueName(88, "Mobliz"),
		models.NewValueName(89, "Mobliz"),
		models.NewValueName(90, "Mobliz"),
		models.NewValueName(91, "Mobliz"),
		models.NewValueName(92, "Nikeah"),
		models.NewValueName(93, "Nikeah"),
		models.NewValueName(94, "Nikeah"),
		models.NewValueName(95, "Nikeah"),
		models.NewValueName(96, "Nikeah"),
		models.NewValueName(97, "Kohlingen"),
		models.NewValueName(98, "Kohlingen"),
		models.NewValueName(99, "Kohlingen"),
		models.NewValueName(100, "Kohlingen"),
		models.NewValueName(101, "Kohlingen"),
		models.NewValueName(102, "Kohlingen"),
		models.NewValueName(103, "Dragon's Neck Cabin"),
		models.NewValueName(104, "Dragon's Neck Cabin"),
		models.NewValueName(105, "Jidoor"),
		models.NewValueName(106, "Jidoor"),
		models.NewValueName(107, "Jidoor"),
		models.NewValueName(108, "Jidoor"),
		models.NewValueName(109, "Jidoor"),
		models.NewValueName(110, "Jidoor"),
		models.NewValueName(111, "Jidoor"),
		models.NewValueName(112, "Opera House"),
		models.NewValueName(113, "Opera House"),
		models.NewValueName(114, "Opera House"),
		models.NewValueName(115, "Opera House"),
		models.NewValueName(116, "Opera House"),
		models.NewValueName(117, "Opera House"),
		models.NewValueName(118, "Opera House"),
		models.NewValueName(119, "Blackjack"),
		models.NewValueName(120, "Blackjack"),
		models.NewValueName(121, "Blackjack"),
		models.NewValueName(122, "Blackjack"),
		models.NewValueName(123, "Blackjack"),
		models.NewValueName(124, "Blackjack"),
		models.NewValueName(125, "Albrook"),
		models.NewValueName(126, "Albrook"),
		models.NewValueName(127, "Albrook"),
		models.NewValueName(128, "Albrook"),
		models.NewValueName(129, "Albrook"),
		models.NewValueName(130, "Albrook"),
		models.NewValueName(131, "Albrook"),
		models.NewValueName(132, "Tzen"),
		models.NewValueName(133, "Tzen"),
		models.NewValueName(134, "Tzen"),
		models.NewValueName(135, "Tzen"),
		models.NewValueName(136, "Tzen"),
		models.NewValueName(137, "Tzen"),
		models.NewValueName(138, "Maranda"),
		models.NewValueName(139, "Maranda"),
		models.NewValueName(140, "Maranda"),
		models.NewValueName(141, "Maranda"),
		models.NewValueName(142, "Maranda"),
		models.NewValueName(143, "Vector"),
		models.NewValueName(144, "Vector"),
		models.NewValueName(145, "Vector"),
		models.NewValueName(146, "Vector"),
		models.NewValueName(147, "Vector"),
		models.NewValueName(148, "Vector"),
		models.NewValueName(149, "Vector"),
		models.NewValueName(150, "Vector"),
		models.NewValueName(151, "Vector"),
		models.NewValueName(152, "Vector"),
		models.NewValueName(153, "Vector"),
		models.NewValueName(154, "Vector"),
		models.NewValueName(155, "Esper World"),
		models.NewValueName(156, "Esper World"),
		models.NewValueName(157, "Esper World"),
		models.NewValueName(158, "Esper World"),
		models.NewValueName(159, "Esper World"),
		models.NewValueName(160, "Esper World"),
		models.NewValueName(161, "Esper World"),
		models.NewValueName(162, "Imperial Observation Post"),
		models.NewValueName(163, "Imperial Observation Post"),
		models.NewValueName(164, "Imperial Observation Post"),
		models.NewValueName(165, "Imperial Palace"),
		models.NewValueName(166, "Imperial Palace"),
		models.NewValueName(167, "Imperial Palace"),
		models.NewValueName(168, "Imperial Palace"),
		models.NewValueName(169, "Imperial Palace"),
		models.NewValueName(170, "Imperial Palace"),
		models.NewValueName(171, "Imperial Palace"),
		models.NewValueName(172, "Imperial Palace"),
		models.NewValueName(173, "Imperial Palace"),
		models.NewValueName(174, "Imperial Palace"),
		models.NewValueName(175, "Imperial Palace"),
		models.NewValueName(176, "Imperial Palace"),
		models.NewValueName(177, "Imperial Palace"),
		models.NewValueName(178, "Imperial Palace"),
		models.NewValueName(179, "Imperial Palace"),
		models.NewValueName(180, "Thamasa"),
		models.NewValueName(181, "Thamasa"),
		models.NewValueName(182, "Thamasa"),
		models.NewValueName(183, "Thamasa"),
		models.NewValueName(184, "Thamasa"),
		models.NewValueName(185, "Thamasa"),
		models.NewValueName(186, "Thamasa"),
		models.NewValueName(187, "Thamasa"),
		models.NewValueName(188, "Chocobo Stable"),
		models.NewValueName(189, "Chocobo Stable"),
		models.NewValueName(190, "Solitary Island"),
		models.NewValueName(191, "Solitary Island"),
		models.NewValueName(192, "Solitary Island"),
		models.NewValueName(193, "Solitary Island"),
		models.NewValueName(194, "Albrook"),
		models.NewValueName(195, "Albrook"),
		models.NewValueName(196, "Albrook"),
		models.NewValueName(197, "Albrook"),
		models.NewValueName(198, "Albrook"),
		models.NewValueName(199, "Albrook"),
		models.NewValueName(200, "Albrook"),
		models.NewValueName(201, "Tzen"),
		models.NewValueName(202, "Tzen"),
		models.NewValueName(203, "Tzen"),
		models.NewValueName(204, "Tzen"),
		models.NewValueName(205, "Tzen"),
		models.NewValueName(206, "Tzen"),
		models.NewValueName(207, "Mobliz"),
		models.NewValueName(208, "Mobliz"),
		models.NewValueName(209, "Mobliz"),
		models.NewValueName(210, "Mobliz"),
		models.NewValueName(211, "Mobliz"),
		models.NewValueName(212, "Mobliz"),
		models.NewValueName(213, "Mobliz"),
		models.NewValueName(214, "Nikeah"),
		models.NewValueName(215, "Nikeah"),
		models.NewValueName(216, "Nikeah"),
		models.NewValueName(217, "Nikeah"),
		models.NewValueName(218, "Nikeah"),
		models.NewValueName(219, "South Figaro"),
		models.NewValueName(220, "South Figaro"),
		models.NewValueName(221, "South Figaro"),
		models.NewValueName(222, "South Figaro"),
		models.NewValueName(223, "South Figaro"),
		models.NewValueName(224, "South Figaro"),
		models.NewValueName(225, "South Figaro"),
		models.NewValueName(226, "South Figaro"),
		models.NewValueName(227, "South Figaro"),
		models.NewValueName(228, "South Figaro"),
		models.NewValueName(229, "South Figaro"),
		models.NewValueName(230, "South Figaro"),
		models.NewValueName(231, "South Figaro"),
		models.NewValueName(232, "South Figaro"),
		models.NewValueName(233, "South Figaro"),
		models.NewValueName(234, "South Figaro"),
		models.NewValueName(235, "South Figaro"),
		models.NewValueName(236, "South Figaro"),
		models.NewValueName(237, "South Figaro"),
		models.NewValueName(238, "South Figaro"),
		models.NewValueName(239, "South Figaro"),
		models.NewValueName(240, "South Figaro"),
		models.NewValueName(241, "South Figaro"),
		models.NewValueName(242, "South Figaro"),
		models.NewValueName(243, "South Figaro"),
		models.NewValueName(244, "South Figaro"),
		models.NewValueName(245, "South Figaro"),
		models.NewValueName(246, "South Figaro"),
		models.NewValueName(247, "Figaro Castle"),
		models.NewValueName(248, "Figaro Castle"),
		models.NewValueName(249, "Figaro Castle"),
		models.NewValueName(250, "Figaro Castle"),
		models.NewValueName(251, "Figaro Castle"),
		models.NewValueName(252, "Figaro Castle"),
		models.NewValueName(253, "Figaro Castle"),
		models.NewValueName(254, "Figaro Castle"),
		models.NewValueName(255, "Figaro Castle"),
		models.NewValueName(256, "Figaro Castle"),
		models.NewValueName(257, "Figaro Castle"),
		models.NewValueName(258, "Figaro Castle"),
		models.NewValueName(259, "Figaro Castle"),
		models.NewValueName(260, "Figaro Castle"),
		models.NewValueName(261, "Figaro Castle"),
		models.NewValueName(262, "Kohlingen"),
		models.NewValueName(263, "Kohlingen"),
		models.NewValueName(264, "Kohlingen"),
		models.NewValueName(265, "Kohlingen"),
		models.NewValueName(266, "Kohlingen"),
		models.NewValueName(267, "Kohlingen"),
		models.NewValueName(268, "Falcon"),
		models.NewValueName(269, "Falcon"),
		models.NewValueName(270, "Falcon"),
		models.NewValueName(271, "Falcon"),
		models.NewValueName(272, "Duncan's Cabin"),
		models.NewValueName(273, "Duncan's Cabin"),
		models.NewValueName(274, "Maranda"),
		models.NewValueName(275, "Maranda"),
		models.NewValueName(276, "Maranda"),
		models.NewValueName(277, "Maranda"),
		models.NewValueName(278, "Maranda"),
		models.NewValueName(279, "Coliseum"),
		models.NewValueName(280, "Coliseum"),
		models.NewValueName(281, "Coliseum"),
		models.NewValueName(282, "Jidoor"),
		models.NewValueName(283, "Jidoor"),
		models.NewValueName(284, "Jidoor"),
		models.NewValueName(285, "Jidoor"),
		models.NewValueName(286, "Jidoor"),
		models.NewValueName(287, "Jidoor"),
		models.NewValueName(288, "Jidoor"),
		models.NewValueName(289, "Jidoor"),
		models.NewValueName(290, "Opera House"),
		models.NewValueName(291, "Opera House"),
		models.NewValueName(292, "Opera House"),
		models.NewValueName(293, "Opera House"),
		models.NewValueName(294, "Opera House"),
		models.NewValueName(295, "Opera House"),
		models.NewValueName(296, "Doma Castle"),
		models.NewValueName(297, "Doma Castle"),
		models.NewValueName(298, "Doma Castle"),
		models.NewValueName(299, "Doma Castle"),
		models.NewValueName(300, "Doma Castle"),
		models.NewValueName(301, "Doma Castle"),
		models.NewValueName(302, "Doma Castle"),
		models.NewValueName(303, "Doma Castle"),
		models.NewValueName(304, "Doma Castle"),
		models.NewValueName(305, "Thamasa"),
		models.NewValueName(306, "Thamasa"),
		models.NewValueName(307, "Thamasa"),
		models.NewValueName(308, "Thamasa"),
		models.NewValueName(309, "Thamasa"),
		models.NewValueName(310, "Thamasa"),
		models.NewValueName(311, "Thamasa"),
		models.NewValueName(312, "Thamasa"),
		models.NewValueName(313, "Cabin"),
		models.NewValueName(314, "Cabin"),
		models.NewValueName(315, "Chocobo Stable"),
		models.NewValueName(316, "Chocobo Stable"),
		models.NewValueName(317, "Narshe Mines"),
		models.NewValueName(318, "Narshe Mines"),
		models.NewValueName(319, "Narshe Mines"),
		models.NewValueName(320, "Narshe Mines"),
		models.NewValueName(321, "Narshe Mines"),
		models.NewValueName(322, "Narshe Mines"),
		models.NewValueName(323, "Narshe Mines"),
		models.NewValueName(324, "Narshe Mines"),
		models.NewValueName(325, "Narshe Mines"),
		models.NewValueName(326, "Narshe Mines"),
		models.NewValueName(327, "Narshe Mines"),
		models.NewValueName(328, "South Figaro Cave"),
		models.NewValueName(329, "South Figaro Cave"),
		models.NewValueName(330, "South Figaro Cave"),
		models.NewValueName(331, "South Figaro Cave"),
		models.NewValueName(332, "South Figaro Cave"),
		models.NewValueName(333, "South Figaro Cave"),
		models.NewValueName(334, "Mt. Kolts"),
		models.NewValueName(335, "Mt. Kolts"),
		models.NewValueName(336, "Mt. Kolts"),
		models.NewValueName(337, "Mt. Kolts"),
		models.NewValueName(338, "Mt. Kolts"),
		models.NewValueName(339, "Mt. Kolts"),
		models.NewValueName(340, "Mt. Kolts"),
		models.NewValueName(341, "Mt. Kolts"),
		models.NewValueName(342, "Mt. Kolts"),
		models.NewValueName(343, "Mt. Kolts"),
		models.NewValueName(344, "Mt. Kolts"),
		models.NewValueName(345, "Lethe River"),
		models.NewValueName(346, "Lethe River"),
		models.NewValueName(347, "Lethe River"),
		models.NewValueName(348, "Lethe River"),
		models.NewValueName(349, "Lethe River"),
		models.NewValueName(350, "Imperial Camp"),
		models.NewValueName(351, "Phantom Forest"),
		models.NewValueName(352, "Phantom Forest"),
		models.NewValueName(353, "Phantom Forest"),
		models.NewValueName(354, "Phantom Forest"),
		models.NewValueName(355, "Platform"),
		models.NewValueName(356, "Phantom Train"),
		models.NewValueName(357, "Phantom Train"),
		models.NewValueName(358, "Phantom Train"),
		models.NewValueName(359, "Phantom Train"),
		models.NewValueName(360, "Phantom Train"),
		models.NewValueName(361, "Phantom Train"),
		models.NewValueName(362, "Phantom Train"),
		models.NewValueName(363, "Phantom Train"),
		models.NewValueName(364, "Phantom Train"),
		models.NewValueName(365, "Phantom Train"),
		models.NewValueName(366, "Phantom Train"),
		models.NewValueName(367, "Phantom Train"),
		models.NewValueName(368, "Phantom Train"),
		models.NewValueName(369, "Phantom Train"),
		models.NewValueName(370, "Phantom Train"),
		models.NewValueName(371, "Phantom Train"),
		models.NewValueName(372, "Platform"),
		models.NewValueName(373, "Cave to Baren Falls"),
		models.NewValueName(374, "Cave to Baren Falls"),
		models.NewValueName(375, "Baren Falls"),
		models.NewValueName(376, "Riverside"),
		models.NewValueName(377, "Crescent Mountain Cave"),
		models.NewValueName(378, "Crescent Mountain Cave"),
		models.NewValueName(379, "Serpent Trench"),
		models.NewValueName(380, "Serpent Trench"),
		models.NewValueName(381, "Serpent Trench"),
		models.NewValueName(382, "Serpent Trench"),
		models.NewValueName(383, "Zozo"),
		models.NewValueName(384, "Zozo"),
		models.NewValueName(385, "Zozo"),
		models.NewValueName(386, "Zozo"),
		models.NewValueName(387, "Zozo"),
		models.NewValueName(388, "Zozo"),
		models.NewValueName(389, "Zozo"),
		models.NewValueName(390, "Zozo"),
		models.NewValueName(391, "Zozo"),
		models.NewValueName(392, "Zozo"),
		models.NewValueName(393, "Zozo"),
		models.NewValueName(394, "Zozo"),
		models.NewValueName(395, "Zozo"),
		models.NewValueName(396, "Magitek Factory"),
		models.NewValueName(397, "Magitek Factory"),
		models.NewValueName(398, "Magitek Factory"),
		models.NewValueName(399, "Magitek Factory"),
		models.NewValueName(400, "Magitek Factory"),
		models.NewValueName(401, "Magitek Research Facility"),
		models.NewValueName(402, "Magitek Research Facility"),
		models.NewValueName(403, "Magitek Research Facility"),
		models.NewValueName(404, "Magitek Research Facility"),
		models.NewValueName(405, "Cave to the Sealed Gate"),
		models.NewValueName(406, "Cave to the Sealed Gate"),
		models.NewValueName(407, "Cave to the Sealed Gate"),
		models.NewValueName(408, "Cave to the Sealed Gate"),
		models.NewValueName(409, "Cave to the Sealed Gate"),
		models.NewValueName(410, "Cave to the Sealed Gate"),
		models.NewValueName(411, "Cave to the Sealed Gate"),
		models.NewValueName(412, "Burning Home"),
		models.NewValueName(413, "Burning Home"),
		models.NewValueName(414, "Burning Home"),
		models.NewValueName(415, "Burning Home"),
		models.NewValueName(416, "Burning Home"),
		models.NewValueName(417, "Burning Home"),
		models.NewValueName(418, "Burning Home"),
		models.NewValueName(419, "Burning Home"),
		models.NewValueName(420, "Burning Home"),
		models.NewValueName(421, "Esper Cave"),
		models.NewValueName(422, "Esper Cave"),
		models.NewValueName(423, "Esper Cave"),
		models.NewValueName(424, "Esper Cave"),
		models.NewValueName(425, "Esper Cave"),
		models.NewValueName(426, "Esper Cave"),
		models.NewValueName(427, "Esper Cave"),
		models.NewValueName(428, "Esper Cave"),
		models.NewValueName(429, "Esper Cave"),
		models.NewValueName(430, "Esper Cave"),
		models.NewValueName(431, "Floating Continent"),
		models.NewValueName(432, "Floating Continent"),
		models.NewValueName(433, "Crumbling House"),
		models.NewValueName(434, "Crumbling House"),
		models.NewValueName(435, "Figaro Castle"),
		models.NewValueName(436, "Figaro Castle"),
		models.NewValueName(437, "Figaro Castle"),
		models.NewValueName(438, "Figaro Castle"),
		models.NewValueName(439, "Figaro Castle"),
		models.NewValueName(440, "Figaro Castle"),
		models.NewValueName(441, "Figaro Castle"),
		models.NewValueName(442, "Owzer's Mansion"),
		models.NewValueName(443, "Owzer's Mansion"),
		models.NewValueName(444, "Owzer's Mansion"),
		models.NewValueName(445, "Owzer's Mansion"),
		models.NewValueName(446, "Owzer's Mansion"),
		models.NewValueName(447, "Scenario Selection"),
		models.NewValueName(448, "South Figaro Cave"),
		models.NewValueName(449, "South Figaro Cave"),
		models.NewValueName(450, "South Figaro Cave"),
		models.NewValueName(451, "South Figaro Cave"),
		models.NewValueName(452, "South Figaro Cave"),
		models.NewValueName(453, "South Figaro Cave"),
		models.NewValueName(454, "South Figaro Cave"),
		models.NewValueName(455, "Darill's Tomb"),
		models.NewValueName(456, "Darill's Tomb"),
		models.NewValueName(457, "Darill's Tomb"),
		models.NewValueName(458, "Darill's Tomb"),
		models.NewValueName(459, "Darill's Tomb"),
		models.NewValueName(460, "Darill's Tomb"),
		models.NewValueName(461, "Darill's Tomb"),
		models.NewValueName(462, "Darill's Tomb"),
		models.NewValueName(463, "Darill's Tomb"),
		models.NewValueName(464, "Darill's Tomb"),
		models.NewValueName(465, "Darill's Tomb"),
		models.NewValueName(466, "Darill's Tomb"),
		models.NewValueName(467, "Darill's Tomb"),
		models.NewValueName(468, "Darill's Tomb"),
		models.NewValueName(469, "Mt. Zozo"),
		models.NewValueName(470, "Mt. Zozo"),
		models.NewValueName(471, "Mt. Zozo"),
		models.NewValueName(472, "Mt. Zozo"),
		models.NewValueName(473, "Mt. Zozo"),
		models.NewValueName(474, "Mt. Zozo"),
		models.NewValueName(475, "Mt. Zozo"),
		models.NewValueName(476, "Cultists' Tower"),
		models.NewValueName(477, "Cultists' Tower"),
		models.NewValueName(478, "Cultists' Tower"),
		models.NewValueName(479, "Cultists' Tower"),
		models.NewValueName(480, "Cultists' Tower"),
		models.NewValueName(481, "Cultists' Tower"),
		models.NewValueName(482, "Cultists' Tower"),
		models.NewValueName(483, "Cultists' Tower"),
		models.NewValueName(484, "Cultists' Tower"),
		models.NewValueName(485, "Cultists' Tower"),
		models.NewValueName(486, "Cultists' Tower"),
		models.NewValueName(487, "Cultists' Tower"),
		models.NewValueName(488, "Cave on the Veldt"),
		models.NewValueName(489, "Cave on the Veldt"),
		models.NewValueName(490, "Cave on the Veldt"),
		models.NewValueName(491, "Cave on the Veldt"),
		models.NewValueName(492, "Cave on the Veldt"),
		models.NewValueName(493, "Yeti's Cave"),
		models.NewValueName(494, "Yeti's Cave"),
		models.NewValueName(495, "Yeti's Cave"),
		models.NewValueName(496, "Yeti's Cave"),
		models.NewValueName(497, "Phoenix Cave"),
		models.NewValueName(498, "Phoenix Cave"),
		models.NewValueName(499, "Phoenix Cave"),
		models.NewValueName(500, "Zone Eater's Belly"),
		models.NewValueName(501, "Zone Eater's Belly"),
		models.NewValueName(502, "Zone Eater's Belly"),
		models.NewValueName(503, "Zone Eater's Belly"),
		models.NewValueName(504, "Zone Eater's Belly"),
		models.NewValueName(505, "Zone Eater's Belly"),
		models.NewValueName(506, "Zone Eater's Belly"),
		models.NewValueName(507, "Zone Eater's Belly"),
		models.NewValueName(508, "Cave to the Ancient Castle"),
		models.NewValueName(509, "Cave to the Ancient Castle"),
		models.NewValueName(510, "Cave to the Ancient Castle"),
		models.NewValueName(511, "Cave to the Ancient Castle"),
		models.NewValueName(512, "Ancient Castle"),
		models.NewValueName(513, "Ancient Castle"),
		models.NewValueName(514, "Ancient Castle"),
		models.NewValueName(515, "Ancient Castle"),
		models.NewValueName(516, "Ancient Castle"),
		models.NewValueName(517, "Ancient Castle"),
		models.NewValueName(518, "Ancient Castle"),
		models.NewValueName(519, "Ancient Castle"),
		models.NewValueName(520, "Dreamscape"),
		models.NewValueName(521, "Dreamscape"),
		models.NewValueName(522, "Dreamscape - Phantom Train"),
		models.NewValueName(523, "Dreamscape - Phantom Train"),
		models.NewValueName(524, "Dreamscape - Phantom Train"),
		models.NewValueName(525, "Dreamscape - Phantom Train"),
		models.NewValueName(526, "Dreamscape - Phantom Train"),
		models.NewValueName(527, "Dreamscape - Phantom Train"),
		models.NewValueName(528, "Dreamscape - Cave"),
		models.NewValueName(529, "Dreamscape - Cave"),
		models.NewValueName(530, "Dreamscape - Doma Castle"),
		models.NewValueName(531, "Dreamscape - Doma Castle"),
		models.NewValueName(532, "Dreamscape - Doma Castle"),
		models.NewValueName(533, "Dreamscape - Doma Castle"),
		models.NewValueName(534, "Dreamscape - Doma Castle"),
		models.NewValueName(535, "Dreamscape - Doma Castle"),
		models.NewValueName(536, "Dreamscape - Doma Castle"),
		models.NewValueName(537, "Dreamscape - Doma Castle"),
		models.NewValueName(538, "Dreamscape - Doma Castle"),
		models.NewValueName(539, "Ebot's Rock"),
		models.NewValueName(540, "Ebot's Rock"),
		models.NewValueName(541, "Ebot's Rock"),
		models.NewValueName(542, "Kefka's Tower"),
		models.NewValueName(543, "Kefka's Tower"),
		models.NewValueName(544, "Kefka's Tower"),
		models.NewValueName(545, "Kefka's Tower"),
		models.NewValueName(546, "Kefka's Tower"),
		models.NewValueName(547, "Kefka's Tower"),
		models.NewValueName(548, "Kefka's Tower"),
		models.NewValueName(549, "Kefka's Tower"),
		models.NewValueName(550, "Kefka's Tower"),
		models.NewValueName(551, "Kefka's Tower"),
		models.NewValueName(552, "Kefka's Tower"),
		models.NewValueName(553, "Kefka's Tower"),
		models.NewValueName(554, "Kefka's Tower"),
		models.NewValueName(555, "Kefka's Tower"),
		models.NewValueName(556, "Kefka's Tower"),
		models.NewValueName(557, "Kefka's Tower"),
		models.NewValueName(558, "Kefka's Tower"),
		models.NewValueName(559, "Kefka's Tower"),
		models.NewValueName(560, "Kefka's Tower"),
		models.NewValueName(561, "Kefka's Tower"),
		models.NewValueName(562, "Kefka's Tower"),
		models.NewValueName(563, "Kefka's Tower"),
		models.NewValueName(564, "Kefka's Tower"),
		models.NewValueName(565, "Kefka's Tower"),
		models.NewValueName(566, "Kefka's Tower"),
		models.NewValueName(567, "Kefka's Tower"),
		models.NewValueName(568, "Kefka's Tower"),
		models.NewValueName(569, "Kefka's Tower"),
		models.NewValueName(570, "Kefka's Tower"),
		models.NewValueName(571, "Kefka's Tower"),
		models.NewValueName(572, "Overworld"),
		models.NewValueName(573, "Overworld"),
		models.NewValueName(574, "Opera House"),
		models.NewValueName(575, "Overworld"),
		models.NewValueName(576, "Opera House"),
		models.NewValueName(577, "Darill's Tomb"),
		models.NewValueName(578, "Overworld"),
		models.NewValueName(579, "Darill's Tomb"),
		models.NewValueName(580, "Narshe Mines"),
		models.NewValueName(581, "Narshe"),
		models.NewValueName(582, "Blackjack"),
		models.NewValueName(583, "Mobliz"),
		models.NewValueName(584, "Scenario Selection"),
		models.NewValueName(585, "Falcon"),
		models.NewValueName(586, "Overworld"),
		models.NewValueName(587, "Figaro Castle"),
		models.NewValueName(588, "Figaro Castle"),
		models.NewValueName(589, "Figaro Castle"),
		models.NewValueName(590, "Kefka's Tower"),
		models.NewValueName(591, "Scenario Selection"),
		models.NewValueName(592, "Scenario Selection"),
		models.NewValueName(593, "Scenario Selection"),
		models.NewValueName(594, "Scenario Selection"),
		models.NewValueName(595, "Scenario Selection"),
		models.NewValueName(596, "Scenario Selection"),
		models.NewValueName(597, "Solitary Island"),
		models.NewValueName(598, "Overworld"),
		models.NewValueName(599, "Overworld"),
		models.NewValueName(600, "Overworld"),
		models.NewValueName(601, "Scenario Selection"),
		models.NewValueName(602, "Scenario Selection"),
		models.NewValueName(603, "Scenario Selection"),
		models.NewValueName(604, "Esper World"),
		models.NewValueName(605, "Scenario Selection"),
		models.NewValueName(609, "Narshe"),
		models.NewValueName(610, "Jidoor"),
		models.NewValueName(611, "Jidoor"),
		models.NewValueName(612, "Chocobo Stable"),
		models.NewValueName(613, "Chocobo Stable"),
		models.NewValueName(614, "Chocobo Stable"),
		models.NewValueName(615, "Chocobo Stable"),
		models.NewValueName(616, "Chocobo Stable"),
		models.NewValueName(617, "Chocobo Stable"),
		models.NewValueName(618, "Chocobo Stable"),
		models.NewValueName(619, "Chocobo Stable"),
		models.NewValueName(620, "Chocobo Stable"),
		models.NewValueName(621, "Chocobo Stable"),
		models.NewValueName(622, "Nikeah"),
		models.NewValueName(623, "Albrook"),
		models.NewValueName(624, "Phantom Train"),
		models.NewValueName(625, "Magitek Research Facility"),
		models.NewValueName(626, "South Figaro Cave"),
		models.NewValueName(627, "South Figaro Cave"),
		models.NewValueName(628, "South Figaro Cave"),
		models.NewValueName(629, "South Figaro Cave"),
		models.NewValueName(630, "South Figaro Cave"),
		models.NewValueName(631, "Floating Continent"),
		models.NewValueName(632, "Narshe Mines"),
		models.NewValueName(633, "Narshe Mines"),
		models.NewValueName(634, "Narshe Mines"),
		models.NewValueName(635, "Narshe Mines"),
		models.NewValueName(636, "Narshe Mines"),
		models.NewValueName(637, "Narshe Mines"),
		models.NewValueName(638, "Narshe Mines"),
		models.NewValueName(639, "Narshe Mines"),
		models.NewValueName(641, "Floating Continent"),
		models.NewValueName(642, "Mt. Kolts"),
		models.NewValueName(643, "Magitek Factory"),
		models.NewValueName(800, "Overworld"),
		models.NewValueName(801, "Overworld"),
		models.NewValueName(802, "Overworld"),
		models.NewValueName(803, "Overworld"),
		models.NewValueName(804, "Overworld"),
		models.NewValueName(805, "Overworld"),
	}
)
