package ff6

import (
	"pixel-remastered-save-editor/models"
)

var (
	Weapons = []models.NameValue{
		models.NewValueName(93, "[Empty Hand]"),
		models.NewValueName(94, "Dagger"),
		models.NewValueName(95, "Mythril Knife"),
		models.NewValueName(96, "Main Gauche"),
		models.NewValueName(97, "Air Knife"),
		models.NewValueName(98, "Thief's Knife"),
		models.NewValueName(99, "Assassin's Dagger"),
		models.NewValueName(100, "Man-Eater"),
		models.NewValueName(101, "Swordbreaker"),
		models.NewValueName(102, "Gladius"),
		models.NewValueName(103, "Valiant Knife"),
		models.NewValueName(104, "Mythril Sword"),
		models.NewValueName(105, "Great Sword"),
		models.NewValueName(106, "Rune Blade"),
		models.NewValueName(107, "Flametongue"),
		models.NewValueName(108, "Icebrand"),
		models.NewValueName(109, "Thunder Blade"),
		models.NewValueName(110, "Bastard Sword "),
		models.NewValueName(111, "Break Blade"),
		models.NewValueName(112, "Blood Sword"),
		models.NewValueName(113, "Enhancer"),
		models.NewValueName(114, "Crystal Sword"),
		models.NewValueName(115, "Falchion"),
		models.NewValueName(116, "Soul Sabre"),
		models.NewValueName(117, "Organyx"),
		models.NewValueName(118, "Excalibur"),
		models.NewValueName(119, "Zantetsuken"),
		models.NewValueName(120, "Lightbringer"),
		models.NewValueName(121, "Ragnarok"),
		models.NewValueName(122, "Ultima Weapon"),
		models.NewValueName(123, "Mythril Spear"),
		models.NewValueName(124, "Trident"),
		models.NewValueName(125, "Heavy Lance"),
		models.NewValueName(126, "Partisan"),
		models.NewValueName(127, "Holy Lance"),
		models.NewValueName(128, "Golden Lance"),
		models.NewValueName(129, "Radiant Lance"),
		models.NewValueName(130, "Impartisan"),
		models.NewValueName(131, "Kunai"),
		models.NewValueName(132, "Kodachi"),
		models.NewValueName(133, "Sakura"),
		models.NewValueName(134, "Sasuke"),
		models.NewValueName(135, "Ichigeki"),
		models.NewValueName(136, "Kagenui"),
		models.NewValueName(137, "Ashura"),
		models.NewValueName(138, "Kotetsu"),
		models.NewValueName(139, "Kikuichimonji"),
		models.NewValueName(140, "Kazekiri"),
		models.NewValueName(141, "Murasame"),
		models.NewValueName(142, "Masamune"),
		models.NewValueName(143, "Murakumo"),
		models.NewValueName(144, "Mutsunokami"),
		models.NewValueName(145, "Heal Rod"),
		models.NewValueName(146, "Mythril Rod"),
		models.NewValueName(147, "Flame Rod"),
		models.NewValueName(148, "Ice Rod"),
		models.NewValueName(149, "Thunder Rod"),
		models.NewValueName(150, "Poison Rod"),
		models.NewValueName(151, "Holy Rod"),
		models.NewValueName(152, "Gravity Rod"),
		models.NewValueName(153, "Punisher"),
		models.NewValueName(154, "Magus Rod"),
		models.NewValueName(155, "Chocobo Brush"),
		models.NewValueName(156, "Da Vinci Brush"),
		models.NewValueName(157, "Magical Brush"),
		models.NewValueName(158, "Rainbow Brush"),
		models.NewValueName(159, "Shuriken"),
		models.NewValueName(160, "Fuma Shuriken"),
		models.NewValueName(161, "Pinwheel"),
		models.NewValueName(162, "Chain Flail"),
		models.NewValueName(163, "Moonring Blade"),
		models.NewValueName(164, "Morning Star"),
		models.NewValueName(165, "Boomerang"),
		models.NewValueName(166, "Rising Sun"),
		models.NewValueName(167, "Hawkeye"),
		models.NewValueName(168, "Bone Club"),
		models.NewValueName(169, "Sniper"),
		models.NewValueName(170, "Wing Edge"),
		models.NewValueName(171, "Cards"),
		models.NewValueName(172, "Darts"),
		models.NewValueName(173, "Death Tarot"),
		models.NewValueName(174, "Viper Darts"),
		models.NewValueName(175, "Dice"),
		models.NewValueName(176, "Fixed Dice"),
		models.NewValueName(177, "Metal Knuckles"),
		models.NewValueName(178, "Mythril Claws"),
		models.NewValueName(179, "Kaiser Knuckles"),
		models.NewValueName(180, "Venom Claws"),
		models.NewValueName(181, "Burning Fist"),
		models.NewValueName(182, "Dragon Claws"),
		models.NewValueName(183, "Tigerfangs"),
	}
)
