package ffv

import (
	"pr_save_editor/consts"
)

var (
	Items = []*consts.Item{
		consts.NewItem(2, "Potion"),
		consts.NewItem(3, "Hi - Potion"),
		consts.NewItem(4, "Phoenix Down"),
		consts.NewItem(5, "Ether"),
		consts.NewItem(6, "Antidote"),
		consts.NewItem(7, "Eye Drops"),
		consts.NewItem(8, "Gold Needle"),
		consts.NewItem(9, "Maiden's Kiss"),
		consts.NewItem(10, "Mallet"),
		consts.NewItem(11, "Holy Water"),
		consts.NewItem(12, "Tent"),
		consts.NewItem(13, "Cottage"),
		consts.NewItem(14, "Elixir"),
		consts.NewItem(15, "Goliath Tonic"),
		consts.NewItem(16, "Power Drink"),
		consts.NewItem(17, "Speed Shake"),
		consts.NewItem(18, "Iron Draft"),
		consts.NewItem(19, "Hero Cocktail"),
		consts.NewItem(20, "Turtle Shell"),
		consts.NewItem(21, "Dragon Fang"),
		consts.NewItem(22, "Dark Matter"),
		consts.NewItem(23, "Magic Lamp"),
		consts.NewItem(24, "Flame Scroll"),
		consts.NewItem(25, "Water Scroll"),
		consts.NewItem(26, "Lightning Scroll"),
		consts.NewItem(27, "Ash"),
		consts.NewItem(28, "Shuriken"),
		consts.NewItem(29, "Fuma Shuriken"),
		consts.NewItem(33, "Ramuh"),
		consts.NewItem(34, "Catoblepas"),
		consts.NewItem(35, "Golem"),
		consts.NewItem(36, "Dragon Seal"),
		consts.NewItem(37, "Omega Badge"),
		consts.NewItem(56, "World Map"),
	}
	ImportantItems = []*consts.Item{
		consts.NewItem(39, "Galuf's Bangle"),
		consts.NewItem(40, "Memento"),
		consts.NewItem(42, "Pendant"),
		consts.NewItem(43, "Pendant"),
		consts.NewItem(44, "Canal Key"),
		consts.NewItem(45, "Dragon Grass"),
		consts.NewItem(47, "Adamantite"),
		consts.NewItem(49, "Whisperweed"),
		consts.NewItem(50, "Guardian Branch"),
		consts.NewItem(51, "Sealed Tome"),
		consts.NewItem(52, "First Tablet"),
		consts.NewItem(53, "Second Tablet"),
		consts.NewItem(54, "Third Tablet"),
		consts.NewItem(55, "Fourth Tablet"),
		consts.NewItem(56, "World Map"),
		consts.NewItem(57, "Splinter"),
		consts.NewItem(58, "Dungeon Key"),
	}
	Weapons = []*consts.Item{
		consts.NewItem(39, "Galuf's Bangle"),
		consts.NewItem(40, "Memento"),
		consts.NewItem(42, "Pendant"),
		consts.NewItem(43, "Pendant"),
		consts.NewItem(44, "Canal Key"),
		consts.NewItem(45, "Dragon Grass"),
		consts.NewItem(47, "Adamantite"),
		consts.NewItem(49, "Whisperweed"),
		consts.NewItem(50, "Guardian Branch"),
		consts.NewItem(51, "Sealed Tome"),
		consts.NewItem(52, "First Tablet"),
		consts.NewItem(53, "Second Tablet"),
		consts.NewItem(54, "Third Tablet"),
		consts.NewItem(55, "Fourth Tablet"),
		consts.NewItem(57, "Splinter"),
		consts.NewItem(58, "Dungeon Key"),
		consts.NewItem(60, "Knife"),
		consts.NewItem(61, "Dagger"),
		consts.NewItem(62, "Mythril Knife"),
		consts.NewItem(63, "Mage Masher"),
		consts.NewItem(64, "Main Gauche"),
		consts.NewItem(65, "Orichalcum Dirk"),
		consts.NewItem(66, "Dancing Dagger"),
		consts.NewItem(67, "Air Knife"),
		consts.NewItem(68, "Thief Knife"),
		consts.NewItem(69, "Assassin's Dagger"),
		consts.NewItem(70, "Man-Eater"),
		consts.NewItem(72, "Chicken Knife"),
		consts.NewItem(73, "Kunai"),
		consts.NewItem(74, "Kodachi"),
		consts.NewItem(75, "Sasuke's Katana"),
		consts.NewItem(77, "Broadsword"),
		consts.NewItem(78, "Long Sword"),
		consts.NewItem(79, "Mythril Sword"),
		consts.NewItem(80, "Coral Sword"),
		consts.NewItem(81, "Ancient Sword"),
		consts.NewItem(82, "Sleep Blade"),
		consts.NewItem(83, "Rune Blade"),
		consts.NewItem(84, "Great Sword"),
		consts.NewItem(85, "Excalipoor"),
		consts.NewItem(86, "Enhancer"),
		consts.NewItem(88, "Flametongue"),
		consts.NewItem(89, "Icebrand"),
		consts.NewItem(90, "Blood Sword"),
		consts.NewItem(91, "Defender"),
		consts.NewItem(92, "Excalibur"),
		consts.NewItem(93, "Ragnarok"),
		consts.NewItem(95, "Brave Blade"),
		consts.NewItem(96, "Spear"),
		consts.NewItem(97, "Mythril Spear"),
		consts.NewItem(98, "Trident"),
		consts.NewItem(99, "Wind Spear"),
		consts.NewItem(100, "Heavy Lance"),
		consts.NewItem(101, "Javelin"),
		consts.NewItem(102, "Twin Lance"),
		consts.NewItem(103, "Partisan"),
		consts.NewItem(104, "Holy Lance"),
		consts.NewItem(105, "Dragon Lance"),
		consts.NewItem(107, "Battle Axe"),
		consts.NewItem(108, "Mythril Hammer"),
		consts.NewItem(109, "Ogre Killer"),
		consts.NewItem(110, "War Hammer"),
		consts.NewItem(111, "Death Sickle"),
		consts.NewItem(112, "Poison Axe"),
		consts.NewItem(113, "Gaia Hammer"),
		consts.NewItem(114, "Rune Axe"),
		consts.NewItem(115, "Thor's Hammer"),
		consts.NewItem(116, "Titan's Axe"),
		consts.NewItem(118, "Ashura"),
		consts.NewItem(119, "Wind Slash"),
		consts.NewItem(120, "Osafune"),
		consts.NewItem(121, "Kotetsu"),
		consts.NewItem(122, "Kikuichimonji"),
		consts.NewItem(123, "Murasame"),
		consts.NewItem(124, "Masamune"),
		consts.NewItem(125, "Murakumo"),
		consts.NewItem(127, "Rod"),
		consts.NewItem(128, "Flame Rod"),
		consts.NewItem(129, "Frost Rod"),
		consts.NewItem(130, "Thunder Rod"),
		consts.NewItem(131, "Poison Rod"),
		consts.NewItem(132, "Lilith Rod"),
		consts.NewItem(133, "Magus Rod"),
		consts.NewItem(134, "Wonder Wand"),
		consts.NewItem(136, "Staff"),
		consts.NewItem(137, "Healing Staff"),
		consts.NewItem(138, "Power Staff"),
		consts.NewItem(139, "Staff of Light"),
		consts.NewItem(140, "Sage's Staff"),
		consts.NewItem(141, "Judgment Staff"),
		consts.NewItem(143, "Flail"),
		consts.NewItem(144, "Morning Star"),
		consts.NewItem(145, "Silver Bow"),
		consts.NewItem(146, "Flame Bow"),
		consts.NewItem(147, "Frost Bow"),
		consts.NewItem(148, "Thunder Bow"),
		consts.NewItem(149, "Dark Bow"),
		consts.NewItem(150, "Magic Bow"),
		consts.NewItem(151, "Killer Bow"),
		consts.NewItem(152, "Elven Bow"),
		consts.NewItem(153, "Hayate Bow"),
		consts.NewItem(154, "Aevis Killer"),
		consts.NewItem(155, "Yoichi's Bow"),
		consts.NewItem(156, "Artemis's Bow"),
		consts.NewItem(158, "Silver Harp"),
		consts.NewItem(159, "Dream Harp"),
		consts.NewItem(160, "Lamia's Harp"),
		consts.NewItem(161, "Apollo's Harp"),
		consts.NewItem(162, "Whip"),
		consts.NewItem(163, "Blitz Whip"),
		consts.NewItem(164, "Chain Whip"),
		consts.NewItem(165, "Beast Killer"),
		consts.NewItem(166, "Fire Lash"),
		consts.NewItem(167, "Dragon's Whisker"),
		consts.NewItem(168, "Diamond Bell"),
		consts.NewItem(169, "Gaia Bell"),
		consts.NewItem(170, "Rune Chime"),
		consts.NewItem(171, "Tinklebell"),
		consts.NewItem(172, "Moonring Blade"),
		consts.NewItem(173, "Rising Sun"),
	}
	Armors = []*consts.Item{
		consts.NewItem(178, "Leather Shield"),
		consts.NewItem(179, "Bronze Shield"),
		consts.NewItem(180, "Iron Shield"),
		consts.NewItem(181, "Mythril Shield"),
		consts.NewItem(182, "Golden Shield"),
		consts.NewItem(183, "Aegis Shield"),
		consts.NewItem(184, "Diamond Shield"),
		consts.NewItem(185, "Flame Shield"),
		consts.NewItem(186, "Ice Shield"),
		consts.NewItem(187, "Crystal Shield"),
		consts.NewItem(188, "Genji Shield"),
		consts.NewItem(190, "Leather Cap"),
		consts.NewItem(191, "Plumed Hat"),
		consts.NewItem(192, "Hypno Crown"),
		consts.NewItem(194, "Green Beret"),
		consts.NewItem(195, "Headband"),
		consts.NewItem(196, "Tiger Mask"),
		consts.NewItem(197, "Black Cowl"),
		consts.NewItem(198, "Lamia's Tiara"),
		consts.NewItem(199, "Wizard's Hat"),
		consts.NewItem(200, "Sage's Miter"),
		consts.NewItem(201, "Circlet"),
		consts.NewItem(202, "Gold Hairpin"),
		consts.NewItem(203, "Ribbon"),
		consts.NewItem(204, "Bronze Helm"),
		consts.NewItem(205, "Iron Helm"),
		consts.NewItem(206, "Mythril Helm"),
		consts.NewItem(207, "Golden Helm"),
		consts.NewItem(208, "Diamond Helm"),
		consts.NewItem(209, "Crystal Helm"),
		consts.NewItem(210, "Genji Helm"),
		consts.NewItem(212, "Thornlet"),
		consts.NewItem(213, "Leather Armor"),
		consts.NewItem(214, "Angel Robe"),
		consts.NewItem(215, "Mirage Vest"),
		consts.NewItem(216, "Rainbow Dress"),
		consts.NewItem(218, "Copper Cuirass"),
		consts.NewItem(219, "Kenpo Gi"),
		consts.NewItem(220, "Silver Plate"),
		consts.NewItem(221, "Ninja Suit"),
		consts.NewItem(222, "Power Sash"),
		consts.NewItem(223, "Diamond Plate"),
		consts.NewItem(224, "Black Garb"),
		consts.NewItem(225, "Bone Mail"),
		consts.NewItem(226, "Cotton Robe"),
		consts.NewItem(227, "Silk Robe"),
		consts.NewItem(228, "Sage's Surplice"),
		consts.NewItem(229, "Gaia Gear"),
		consts.NewItem(230, "Luminous Robe"),
		consts.NewItem(231, "Black Robe"),
		consts.NewItem(232, "White Robe"),
		consts.NewItem(234, "Bronze Armor"),
		consts.NewItem(235, "Iron Armor"),
		consts.NewItem(236, "Mythril Armor"),
		consts.NewItem(237, "Golden Armor"),
		consts.NewItem(238, "Diamond Armor"),
		consts.NewItem(239, "Crystal Armor"),
		consts.NewItem(240, "Genji Armor"),
		consts.NewItem(242, "Mythril Gloves"),
		consts.NewItem(243, "Thief's Gloves"),
		consts.NewItem(244, "Gauntlets"),
		consts.NewItem(245, "Titan's Gloves"),
		consts.NewItem(246, "Genji Gloves"),
		consts.NewItem(247, "Silver Armlet"),
		consts.NewItem(248, "Power Armlet"),
		consts.NewItem(249, "Diamond Armlet"),
		consts.NewItem(251, "Leather Shoes"),
		consts.NewItem(252, "Hermes' Sandals"),
		consts.NewItem(253, "Red Slippers"),
		consts.NewItem(254, "Angel Ring"),
		consts.NewItem(255, "Flame Ring"),
		consts.NewItem(256, "Coral Ring"),
		consts.NewItem(257, "Reflect Ring"),
		consts.NewItem(258, "Protect Ring"),
		consts.NewItem(259, "Cursed Ring"),
		consts.NewItem(260, "Kaiser Knuckles"),
		consts.NewItem(261, "Silver Specs"),
		consts.NewItem(262, "Elven Mantle"),
		consts.NewItem(266, "Kornago Gourd"),
	}
	GeneralLookup   = consts.CreateLookup(Items, Weapons, Armors)
	ImportantLookup = consts.CreateLookup(ImportantItems)
)
