package ff1

import (
	"pixel-remastered-save-editor/models"
)

var (
	Bestiary = []models.NameValue{
		models.NewValueName(1, "Goblin"),
		models.NewValueName(2, "Goblin Guard"),
		models.NewValueName(3, "Wolf"),
		models.NewValueName(4, "Warg Wolf"),
		models.NewValueName(5, "Werewolf"),
		models.NewValueName(6, "Winter Wolf"),
		models.NewValueName(7, "Lizard"),
		models.NewValueName(8, "Fire Lizard"),
		models.NewValueName(9, "Basilisk"),
		models.NewValueName(10, "Hill Gigas"),
		models.NewValueName(11, "Ice Gigas"),
		models.NewValueName(12, "Fire Gigas"),
		models.NewValueName(13, "Sahagin"),
		models.NewValueName(14, "Sahagin Chief"),
		models.NewValueName(15, "Sahagin Prince"),
		models.NewValueName(16, "Pirate"),
		models.NewValueName(17, "Buccaneer"),
		models.NewValueName(18, "Shark"),
		models.NewValueName(19, "White Shark"),
		models.NewValueName(20, "Bigeyes"),
		models.NewValueName(21, "Deepeyes"),
		models.NewValueName(22, "Skeleton"),
		models.NewValueName(23, "Bloodbones"),
		models.NewValueName(24, "Gigas Worm"),
		models.NewValueName(25, "Crawler"),
		models.NewValueName(26, "Hyenadon"),
		models.NewValueName(27, "Hellhound"),
		models.NewValueName(28, "Ogre"),
		models.NewValueName(29, "Ogre Chief"),
		models.NewValueName(30, "Ogre Mage"),
		models.NewValueName(31, "Cobra"),
		models.NewValueName(32, "Anaconda"),
		models.NewValueName(33, "Sea Snake"),
		models.NewValueName(34, "Scorpion"),
		models.NewValueName(35, "Sea Scorpion"),
		models.NewValueName(36, "Minotaur"),
		models.NewValueName(37, "Minotaur Zombie"),
		models.NewValueName(38, "Troll"),
		models.NewValueName(39, "Sea Troll"),
		models.NewValueName(40, "Shadow"),
		models.NewValueName(41, "Wraith"),
		models.NewValueName(42, "Specter"),
		models.NewValueName(43, "Ghost"),
		models.NewValueName(44, "Zombie"),
		models.NewValueName(45, "Ghoul"),
		models.NewValueName(46, "Ghast"),
		models.NewValueName(47, "Wight"),
		models.NewValueName(48, "Purple Worm"),
		models.NewValueName(49, "Sand Worm"),
		models.NewValueName(50, "Lava Worm"),
		models.NewValueName(51, "Evil Eye"),
		models.NewValueName(52, "Death Eye"),
		models.NewValueName(53, "Medusa"),
		models.NewValueName(54, "Earth Medusa"),
		models.NewValueName(55, "Weretiger"),
		models.NewValueName(56, "Rakshasa"),
		models.NewValueName(57, "Ankheg"),
		models.NewValueName(58, "Remorazz"),
		models.NewValueName(59, "Lesser Tiger"),
		models.NewValueName(60, "Sabertooth"),
		models.NewValueName(61, "Vampire"),
		models.NewValueName(62, "Vampire Lord"),
		models.NewValueName(63, "Gargoyle"),
		models.NewValueName(64, "Horned Devil"),
		models.NewValueName(65, "Earth Elemental"),
		models.NewValueName(66, "Fire Elemental"),
		models.NewValueName(67, "White Dragon"),
		models.NewValueName(68, "Red Dragon"),
		models.NewValueName(69, "Dragon Zombie"),
		models.NewValueName(70, "Green Slime"),
		models.NewValueName(71, "Gray Ooze"),
		models.NewValueName(72, "Ochre Jelly"),
		models.NewValueName(73, "Black Flan"),
		models.NewValueName(74, "Black Widow"),
		models.NewValueName(75, "Tarantula"),
		models.NewValueName(76, "Manticore"),
		models.NewValueName(77, "Sphinx"),
		models.NewValueName(78, "Baretta"),
		models.NewValueName(79, "Desert Baretta"),
		models.NewValueName(80, "Mummy"),
		models.NewValueName(81, "King Mummy"),
		models.NewValueName(82, "Cockatrice"),
		models.NewValueName(83, "Pyrolisk"),
		models.NewValueName(84, "Wyvern"),
		models.NewValueName(85, "Wyrm"),
		models.NewValueName(86, "Allosaurus"),
		models.NewValueName(87, "Tyrannosaur"),
		models.NewValueName(88, "Piranha"),
		models.NewValueName(89, "Red Piranha"),
		models.NewValueName(90, "Crocodile"),
		models.NewValueName(91, "White Croc"),
		models.NewValueName(92, "Ochu"),
		models.NewValueName(93, "Neochu"),
		models.NewValueName(94, "Hydra"),
		models.NewValueName(95, "Fire Hydra"),
		models.NewValueName(96, "Guardian"),
		models.NewValueName(97, "Soldier"),
		models.NewValueName(98, "Water Elemental"),
		models.NewValueName(99, "Air Elemental"),
		models.NewValueName(100, "Water Naga"),
		models.NewValueName(101, "Spirit Naga"),
		models.NewValueName(102, "Chimera"),
		models.NewValueName(103, "Rhyos"),
		models.NewValueName(104, "Piscodemon"),
		models.NewValueName(105, "Mindflayer"),
		models.NewValueName(106, "Garland"),
		models.NewValueName(107, "Green Dragon"),
		models.NewValueName(108, "Blue Dragon"),
		models.NewValueName(109, "Clay Golem"),
		models.NewValueName(110, "Stone Golem"),
		models.NewValueName(111, "Iron Golem"),
		models.NewValueName(112, "Black Knight"),
		models.NewValueName(113, "Death Knight"),
		models.NewValueName(114, "Astos"),
		models.NewValueName(115, "Dark Wizard"),
		models.NewValueName(116, "Dark Fighter"),
		models.NewValueName(117, "Crazy Horse"),
		models.NewValueName(118, "Nightmare"),
		models.NewValueName(119, "Warmech"),
		models.NewValueName(120, "Lich"),
		models.NewValueName(121, "Lich"),
		models.NewValueName(122, "Marilith"),
		models.NewValueName(123, "Marilith"),
		models.NewValueName(124, "Kraken"),
		models.NewValueName(125, "Kraken"),
		models.NewValueName(126, "Tiamat"),
		models.NewValueName(127, "Tiamat"),
		models.NewValueName(128, "Chaos"),
		models.NewValueName(129, "Vampire (Cavern of Earth)"),
	}
)
