package ffvi

import (
	"pr_save_editor/consts"
)

var (
	Items = []*consts.Item{
		consts.NewItem(2, "Potion"),
		consts.NewItem(3, "Hi-Potion"),
		consts.NewItem(4, "X-Potion"),
		consts.NewItem(5, "Ether"),
		consts.NewItem(6, "Hi-Ether"),
		consts.NewItem(7, "X-Ether"),
		consts.NewItem(8, "Elixir"),
		consts.NewItem(9, "Megalixir"),
		consts.NewItem(10, "Fenix Down"),
		consts.NewItem(11, "Holy Water"),
		consts.NewItem(12, "Antidote"),
		consts.NewItem(13, "Eye Drops"),
		consts.NewItem(14, "Golden Needle"),
		consts.NewItem(15, "Remedy"),
		consts.NewItem(16, "Sleeping Bag"),
		consts.NewItem(17, "Tent"),
		consts.NewItem(18, "Green Cherry"),
		consts.NewItem(19, "Magicite Shard"),
		consts.NewItem(20, "Super Ball"),
		consts.NewItem(21, "Echo Screen"),
		consts.NewItem(22, "Smoke Bomb"),
		consts.NewItem(23, "Teleport Stone"),
		consts.NewItem(24, "Dried Meat"),
		consts.NewItem(25, "Rename Card"),
		consts.NewItem(31, "Noiseblaster"),
		consts.NewItem(32, "Bioblaster"),
		consts.NewItem(33, "Flash"),
		consts.NewItem(34, "ChainSaw"),
		consts.NewItem(35, "Debilitator"),
		consts.NewItem(36, "Drill"),
		consts.NewItem(37, "Air Anchor"),
		consts.NewItem(38, "Auto Crossbow"),
		consts.NewItem(26, "Fire Scroll"),
		consts.NewItem(27, "Water Scroll"),
		consts.NewItem(28, "Lightning Scroll"),
		consts.NewItem(29, "Invisibility Scroll"),
		consts.NewItem(30, "Shadow Scroll"),
	}
	ImportantItems = []*consts.Item{
		consts.NewItem(39, "Cider"),
		consts.NewItem(40, "Old Clock Key"),
		consts.NewItem(41, "Fish"),
		consts.NewItem(42, "Fish"),
		consts.NewItem(43, "Fish"),
		consts.NewItem(44, "Fish"),
		consts.NewItem(45, "Lump of Metal"),
		consts.NewItem(46, "Lola's Letter"),
		consts.NewItem(47, "Coral"),
		consts.NewItem(48, "Books"),
		consts.NewItem(49, "Emperor's Letter"),
		consts.NewItem(50, "Rush-Rid"),
		consts.NewItem(58, "Pendant"),
	}
	Weapons = []*consts.Item{
		consts.NewItem(94, "Dagger"),
		consts.NewItem(95, "Mythril Knife"),
		consts.NewItem(96, "Main Gauche"),
		consts.NewItem(97, "Air Knife"),
		consts.NewItem(98, "Thief's Knife"),
		consts.NewItem(99, "Assassin's Dagger"),
		consts.NewItem(100, "Man-Eater"),
		consts.NewItem(101, "Swordbreaker"),
		consts.NewItem(102, "Gladius"),
		consts.NewItem(103, "Valiant Knife"),
		consts.NewItem(104, "Mythril Sword"),
		consts.NewItem(105, "Great Sword"),
		consts.NewItem(106, "Rune Blade"),
		consts.NewItem(107, "Flametongue"),
		consts.NewItem(108, "Icebrand"),
		consts.NewItem(109, "Thunder Blade"),
		consts.NewItem(110, "Bastard Sword "),
		consts.NewItem(111, "Break Blade"),
		consts.NewItem(112, "Blood Sword"),
		consts.NewItem(113, "Enhancer"),
		consts.NewItem(114, "Crystal Sword"),
		consts.NewItem(115, "Falchion"),
		consts.NewItem(116, "Soul Sabre"),
		consts.NewItem(117, "Organyx"),
		consts.NewItem(118, "Excalibur"),
		consts.NewItem(119, "Zantetsuken"),
		consts.NewItem(120, "Lightbringer"),
		consts.NewItem(121, "Ragnarok"),
		consts.NewItem(122, "Ultima Weapon"),
		consts.NewItem(123, "Mythril Spear"),
		consts.NewItem(124, "Trident"),
		consts.NewItem(125, "Heavy Lance"),
		consts.NewItem(126, "Partisan"),
		consts.NewItem(127, "Holy Lance"),
		consts.NewItem(128, "Golden Lance"),
		consts.NewItem(129, "Radiant Lance"),
		consts.NewItem(130, "Impartisan"),
		consts.NewItem(131, "Kunai"),
		consts.NewItem(132, "Kodachi"),
		consts.NewItem(133, "Sakura"),
		consts.NewItem(134, "Sasuke"),
		consts.NewItem(135, "Ichigeki"),
		consts.NewItem(136, "Kagenui"),
		consts.NewItem(137, "Ashura"),
		consts.NewItem(138, "Kotetsu"),
		consts.NewItem(139, "Kikuichimonji"),
		consts.NewItem(140, "Kazekiri"),
		consts.NewItem(141, "Murasame"),
		consts.NewItem(142, "Masamune"),
		consts.NewItem(143, "Murakumo"),
		consts.NewItem(144, "Mutsunokami"),
		consts.NewItem(145, "Heal Rod"),
		consts.NewItem(146, "Mythril Rod"),
		consts.NewItem(147, "Flame Rod"),
		consts.NewItem(148, "Ice Rod"),
		consts.NewItem(149, "Thunder Rod"),
		consts.NewItem(150, "Poison Rod"),
		consts.NewItem(151, "Holy Rod"),
		consts.NewItem(152, "Gravity Rod"),
		consts.NewItem(153, "Punisher"),
		consts.NewItem(154, "Magus Rod"),
		consts.NewItem(155, "Chocobo Brush"),
		consts.NewItem(156, "Da Vinci Brush"),
		consts.NewItem(157, "Magical Brush"),
		consts.NewItem(158, "Rainbow Brush"),
		consts.NewItem(159, "Shuriken"),
		consts.NewItem(160, "Fuma Shuriken"),
		consts.NewItem(161, "Pinwheel"),
		consts.NewItem(162, "Chain Flail"),
		consts.NewItem(163, "Moonring Blade"),
		consts.NewItem(164, "Morning Star"),
		consts.NewItem(165, "Boomerang"),
		consts.NewItem(166, "Rising Sun"),
		consts.NewItem(167, "Hawkeye"),
		consts.NewItem(168, "Bone Club"),
		consts.NewItem(169, "Sniper"),
		consts.NewItem(170, "Wing Edge"),
		consts.NewItem(171, "Cards"),
		consts.NewItem(172, "Darts"),
		consts.NewItem(173, "Death Tarot"),
		consts.NewItem(174, "Viper Darts"),
		consts.NewItem(175, "Dice"),
		consts.NewItem(176, "Fixed Dice"),
		consts.NewItem(177, "Metal Knuckles"),
		consts.NewItem(178, "Mythril Claws"),
		consts.NewItem(179, "Kaiser Knuckles"),
		consts.NewItem(180, "Venom Claws"),
		consts.NewItem(181, "Burning Fist"),
		consts.NewItem(182, "Dragon Claws"),
		consts.NewItem(183, "Tigerfangs"),
	}
	Armors = []*consts.Item{
		consts.NewItem(201, "Buckler"),
		consts.NewItem(202, "Heavy Shield"),
		consts.NewItem(203, "Mythril Shield"),
		consts.NewItem(204, "Gold Shield"),
		consts.NewItem(205, "Aegis Shield"),
		consts.NewItem(206, "Diamond Shield"),
		consts.NewItem(207, "Flame Shield"),
		consts.NewItem(208, "Ice Shield"),
		consts.NewItem(209, "Thunder Shield"),
		consts.NewItem(210, "Crystal Shield"),
		consts.NewItem(211, "Genji Shield"),
		consts.NewItem(212, "Tortoise Shield"),
		consts.NewItem(213, "Cursed Shield"),
		consts.NewItem(214, "Paladin Shield"),
		consts.NewItem(215, "Force Shield"),
		consts.NewItem(216, "Leather Hat"),
		consts.NewItem(217, "Hairband"),
		consts.NewItem(218, "Plumed Hat"),
		consts.NewItem(219, "Beret"),
		consts.NewItem(220, "Magus Hat"),
		consts.NewItem(221, "Bandana"),
		consts.NewItem(222, "Iron Helmet"),
		consts.NewItem(223, "Priest's Miter"),
		consts.NewItem(224, "Bard's Hat"),
		consts.NewItem(225, "Green Beret"),
		consts.NewItem(226, "Head Band"),
		consts.NewItem(227, "Mythril Helm"),
		consts.NewItem(228, "Tiara"),
		consts.NewItem(229, "Gold Helmet"),
		consts.NewItem(230, "Tiger Mask"),
		consts.NewItem(231, "Red Hat"),
		consts.NewItem(232, "Mystery Veil"),
		consts.NewItem(233, "Circlet"),
		consts.NewItem(234, "Royal Crown"),
		consts.NewItem(235, "Diamond Helm"),
		consts.NewItem(236, "Black Hood"),
		consts.NewItem(237, "Crystal Helm"),
		consts.NewItem(238, "Oath Veil"),
		consts.NewItem(239, "Cat-Ear Hood"),
		consts.NewItem(240, "Genji Helmet"),
		consts.NewItem(241, "Thornlet"),
		consts.NewItem(242, "Saucer"),
		consts.NewItem(244, "Leather Armor"),
		consts.NewItem(245, "Cotton Robe"),
		consts.NewItem(246, "Kenpo Gi"),
		consts.NewItem(247, "Iron Armor"),
		consts.NewItem(248, "Silk Robe"),
		consts.NewItem(249, "Mythril Vest"),
		consts.NewItem(250, "Ninja Gear"),
		consts.NewItem(251, "White Dress"),
		consts.NewItem(252, "Mythril Mail"),
		consts.NewItem(253, "Gaia Gear"),
		consts.NewItem(254, "Mirage Dress"),
		consts.NewItem(255, "Golden Armor"),
		consts.NewItem(256, "Power Sash"),
		consts.NewItem(257, "Luminous Robe"),
		consts.NewItem(258, "Diamond Vest"),
		consts.NewItem(259, "Red Jacket"),
		consts.NewItem(260, "Force Armor"),
		consts.NewItem(261, "Diamond Armor"),
		consts.NewItem(262, "Black Garb"),
		consts.NewItem(263, "Magus Rove"),
		consts.NewItem(264, "Crystal Mail"),
		consts.NewItem(265, "Regal Gown"),
		consts.NewItem(266, "Genji Armor"),
		consts.NewItem(267, "Reed Cloak"),
		consts.NewItem(268, "Minerva Bustier"),
		consts.NewItem(269, "Tabby Suit"),
		consts.NewItem(270, "Chocobo Suit"),
		consts.NewItem(271, "Moogle Suit"),
		consts.NewItem(272, "Nutkin Suit"),
		consts.NewItem(273, "Behemeth Suit"),
		consts.NewItem(274, "Snow Scarf`"),
	}
	Relics = []*consts.Item{
		consts.NewItem(275, "Silver Spectacles"),
		consts.NewItem(276, "Star Pendant"),
		consts.NewItem(277, "Peace Ring"),
		consts.NewItem(278, "Amulet"),
		consts.NewItem(279, "White Cape"),
		consts.NewItem(280, "Jewel Ring"),
		consts.NewItem(281, "Fairy Ring"),
		consts.NewItem(282, "Barrier Ring"),
		consts.NewItem(283, "Mythril Glove"),
		consts.NewItem(284, "Protect Ring"),
		consts.NewItem(285, "Hermes Sandals"),
		consts.NewItem(286, "Reflect Ring"),
		consts.NewItem(287, "Angel Wings"),
		consts.NewItem(288, "Angel Ring"),
		consts.NewItem(289, "Knight's Code"),
		consts.NewItem(290, "Dragoon Boots"),
		consts.NewItem(291, "Zephyr Cloak"),
		consts.NewItem(292, "Princess Ring"),
		consts.NewItem(293, "Cursed Ring"),
		consts.NewItem(294, "Earring"),
		consts.NewItem(295, "Gigas Glove"),
		consts.NewItem(296, "Blizzard Orb"),
		consts.NewItem(297, "Berserker Ring"),
		consts.NewItem(298, "Thief's Bracer"),
		consts.NewItem(299, "Guard Bracelet"),
		consts.NewItem(300, "Hero Ring"),
		consts.NewItem(301, "Ribbon"),
		consts.NewItem(302, "Muscle Belt"),
		consts.NewItem(303, "Crystal Orb"),
		consts.NewItem(304, "Gold Hairpin"),
		consts.NewItem(305, "Celestriad"),
		consts.NewItem(306, "Brigand's Glove"),
		consts.NewItem(307, "Gauntlet"),
		consts.NewItem(308, "Genji Glove"),
		consts.NewItem(309, "Hyper Wrist"),
		consts.NewItem(310, "Master's Scroll"),
		consts.NewItem(311, "Prayer Beads"),
		consts.NewItem(312, "Black Belt"),
		consts.NewItem(313, "Heiki's Jitte"),
		consts.NewItem(314, "Fake Mustache"),
		consts.NewItem(315, "Soul of Thamasa"),
		consts.NewItem(316, "Dragon Horn"),
		consts.NewItem(317, "Merit Award"),
		consts.NewItem(318, "Momento Ring"),
		consts.NewItem(319, "Safety Bit"),
		consts.NewItem(320, "Lich Ring"),
		consts.NewItem(321, "Molulu's Charm"),
		consts.NewItem(322, "Ward Bangle"),
		consts.NewItem(323, "Miracle Shoes"),
		consts.NewItem(324, "Alarm Gaurd"),
		consts.NewItem(325, "Gale Hairpin"),
		consts.NewItem(326, "Sniper Eye"),
		consts.NewItem(327, "Growth Egg"),
		consts.NewItem(328, "Tintinnabulum"),
		consts.NewItem(329, "Sprint Shoes"),
	}
	GeneralLookup   = consts.CreateLookup(Items, Weapons, Armors, Relics)
	ImportantLookup = consts.CreateLookup(ImportantItems)
)
