package ff5

import (
	"pixel-remastered-save-editor/models"
)

var (
	Abilities = []models.NameValue{
		models.NewValueName(6, "Guard"),
		models.NewValueName(7, "Kick"),
		models.NewValueName(8, "Focus"),
		models.NewValueName(9, "Chakra"),
		models.NewValueName(10, "Scram"),
		models.NewValueName(11, "Steal"),
		models.NewValueName(12, "Mug"),
		models.NewValueName(13, "Jump"),
		models.NewValueName(14, "Lance"),
		models.NewValueName(15, "Smoke"),
		models.NewValueName(16, "Image"),
		models.NewValueName(17, "Throw"),
		models.NewValueName(18, "Mineuchi"),
		models.NewValueName(19, "Zeninage"),
		models.NewValueName(20, "Iainuki"),
		models.NewValueName(21, "Animals"),
		models.NewValueName(22, "Aim"),
		models.NewValueName(23, "Rapid Fire"),
		models.NewValueName(24, "Call"),
		models.NewValueName(25, "Check"),
		models.NewValueName(26, "Scan"),
		models.NewValueName(27, "Calm"),
		models.NewValueName(28, "Control"),
		models.NewValueName(29, "Catch"),
		models.NewValueName(30, "Release"),
		models.NewValueName(31, "Mix"),
		models.NewValueName(32, "Drink"),
		models.NewValueName(33, "Recover"),
		models.NewValueName(34, "Revive"),
		models.NewValueName(35, "Gaia"),
		models.NewValueName(37, "Hide"),
		models.NewValueName(38, "Reveal"),
		models.NewValueName(41, "Flirt"),
		models.NewValueName(42, "Dance"),
		models.NewValueName(43, "Mimic"),
		models.NewValueName(51, "Equip Shields"),
		models.NewValueName(52, "Equip Armor"),
		models.NewValueName(53, "Equip Ribbons"),
		models.NewValueName(54, "Equip Swords"),
		models.NewValueName(55, "Equip Lances"),
		models.NewValueName(56, "Equip Katanas"),
		models.NewValueName(57, "Equip Axes"),
		models.NewValueName(58, "Equip Bows"),
		models.NewValueName(59, "Equip Whips"),
		models.NewValueName(60, "Equip Harps"),
		models.NewValueName(61, "Artful Dodger"),
		models.NewValueName(62, "HP +10%"),
		models.NewValueName(63, "HP +20%"),
		models.NewValueName(64, "HP +30%"),
		models.NewValueName(65, "MP +10%"),
		models.NewValueName(66, "MP +30%"),
		models.NewValueName(67, "Barehanded"),
		models.NewValueName(68, "Two-Handed"),
		models.NewValueName(69, "Dual-Wield"),
		models.NewValueName(70, "Pharmacology"),
		models.NewValueName(71, "Cover"),
		models.NewValueName(72, "Counter"),
		models.NewValueName(73, "Shirahadori"),
		models.NewValueName(74, "Learn"),
		models.NewValueName(75, "Magic Shell"),
		models.NewValueName(76, "Berserk"),
		models.NewValueName(77, "Vigilance"),
		models.NewValueName(78, "First Strike"),
		models.NewValueName(79, "Find Passages"),
		models.NewValueName(80, "Light Step"),
		models.NewValueName(81, "Find Pits"),
		models.NewValueName(82, "Equip Rods"),
		models.NewValueName(83, "Sprint"),
	}

	Spellblade = []models.NameValue{
		models.NewValueName(90, "Fire"),
		models.NewValueName(91, "Blizzard"),
		models.NewValueName(92, "Thunder"),
		models.NewValueName(93, "Poison"),
		models.NewValueName(94, "Silence"),
		models.NewValueName(95, "Sleep"),
		models.NewValueName(96, "Fira"),
		models.NewValueName(97, "Blizzara"),
		models.NewValueName(98, "Thundara"),
		models.NewValueName(99, "Drain"),
		models.NewValueName(100, "Break"),
		models.NewValueName(101, "Bio"),
		models.NewValueName(102, "Firaga"),
		models.NewValueName(103, "Blizzaga"),
		models.NewValueName(104, "Thundaga"),
		models.NewValueName(105, "Holy"),
		models.NewValueName(106, "Flare"),
		models.NewValueName(107, "Osmose"),
	}

	WhiteMagic = []models.NameValue{
		models.NewValueName(108, "Cure"),
		models.NewValueName(109, "Libra"),
		models.NewValueName(110, "Poisona"),
		models.NewValueName(111, "Silence"),
		models.NewValueName(112, "Protect"),
		models.NewValueName(113, "Mini"),
		models.NewValueName(114, "Cura"),
		models.NewValueName(115, "Raise"),
		models.NewValueName(116, "Confuse"),
		models.NewValueName(117, "Blink"),
		models.NewValueName(118, "Shell"),
		models.NewValueName(119, "Esuna"),
		models.NewValueName(120, "Curaga"),
		models.NewValueName(121, "Reflect"),
		models.NewValueName(122, "Berserk"),
		models.NewValueName(123, "Arise"),
		models.NewValueName(124, "Holy"),
		models.NewValueName(125, "Dispel"),
	}

	BlackMagic = []models.NameValue{
		models.NewValueName(126, "Fire"),
		models.NewValueName(127, "Blizzard"),
		models.NewValueName(128, "Thunder"),
		models.NewValueName(129, "Poison"),
		models.NewValueName(130, "Sleep"),
		models.NewValueName(131, "Toad"),
		models.NewValueName(132, "Fira"),
		models.NewValueName(133, "Blizzara"),
		models.NewValueName(134, "Thundara"),
		models.NewValueName(135, "Drain"),
		models.NewValueName(136, "Break"),
		models.NewValueName(137, "Bio"),
		models.NewValueName(138, "Firaga"),
		models.NewValueName(139, "Blizzaga"),
		models.NewValueName(140, "Thundaga"),
		models.NewValueName(141, "Flare"),
		models.NewValueName(142, "Death"),
		models.NewValueName(143, "Osmose"),
	}

	SummonMagic = []models.NameValue{
		models.NewValueName(162, "Chocobo"),
		models.NewValueName(163, "Sylph"),
		models.NewValueName(164, "Remora"),
		models.NewValueName(165, "Shiva"),
		models.NewValueName(166, "Ramuh"),
		models.NewValueName(167, "Ifrit"),
		models.NewValueName(168, "Titan"),
		models.NewValueName(169, "Golem"),
		models.NewValueName(170, "Catoblepas"),
		models.NewValueName(171, "Carbuncle"),
		models.NewValueName(172, "Syldra"),
		models.NewValueName(173, "Odin"),
		models.NewValueName(174, "Phoenix"),
		models.NewValueName(175, "Leviathan"),
		models.NewValueName(176, "Bahamut"),
	}

	TimeMagic = []models.NameValue{
		models.NewValueName(144, "Speed"),
		models.NewValueName(145, "Slow"),
		models.NewValueName(146, "Regen"),
		models.NewValueName(147, "Mute"),
		models.NewValueName(148, "Haste"),
		models.NewValueName(149, "Float"),
		models.NewValueName(150, "Gravity"),
		models.NewValueName(151, "Stop"),
		models.NewValueName(152, "Teleport"),
		models.NewValueName(153, "Comet"),
		models.NewValueName(154, "Slowga"),
		models.NewValueName(155, "Return"),
		models.NewValueName(156, "Graviga"),
		models.NewValueName(157, "Hastega"),
		models.NewValueName(158, "Old"),
		models.NewValueName(159, "Meteor"),
		models.NewValueName(160, "Quick"),
		models.NewValueName(161, "Banish"),
	}

	Songs = []models.NameValue{
		models.NewValueName(195, "Sinewy Etude"),
		models.NewValueName(196, "Swift Song"),
		models.NewValueName(197, "Mighty March"),
		models.NewValueName(198, "Mana's Paean"),
		models.NewValueName(199, "Hero's Rime"),
		models.NewValueName(200, "Requiem"),
		models.NewValueName(201, "Romeo's Ballad"),
		models.NewValueName(202, "Alluring Air"),
	}

	BlueMagic = []models.NameValue{
		models.NewValueName(177, "Choco Kick"),
		models.NewValueName(178, "Whisperwind"),
		models.NewValueName(179, "Constrict"),
		models.NewValueName(180, "Diamond Dust"),
		models.NewValueName(181, "Judgment Bolt"),
		models.NewValueName(182, "Hellfire"),
		models.NewValueName(183, "Gaia's Wrath"),
		models.NewValueName(184, "Earthen Wall"),
		models.NewValueName(185, "Demon Eye"),
		models.NewValueName(186, "Ruby Light"),
		models.NewValueName(187, "Thunderstorm"),
		models.NewValueName(188, "Zantetsuken"),
		models.NewValueName(189, "Flames of Rebirth"),
		models.NewValueName(190, "Tsunami"),
		models.NewValueName(191, "Mega Flare"),
		models.NewValueName(192, "Fat Chocobo"),
		models.NewValueName(193, "Gungnir"),
		models.NewValueName(194, "Flames of Rebirth"),
		models.NewValueName(214, "Potion"),
		models.NewValueName(215, "Lifewater"),
		models.NewValueName(216, "X-Potion"),
		models.NewValueName(217, "Elixir"),
		models.NewValueName(218, "Resurrection"),
		models.NewValueName(219, "Maiden's Kiss"),
		models.NewValueName(220, "Ether"),
		models.NewValueName(222, "Neutralizer"),
		models.NewValueName(223, "Cure Blindness"),
		models.NewValueName(224, "Dragon Power"),
		models.NewValueName(225, "Devil's Juice"),
		models.NewValueName(226, "Hi-Potion"),
		models.NewValueName(227, "Balm of Gilead"),
		models.NewValueName(228, "Triple Ether"),
		models.NewValueName(229, "Reincarnate"),
		models.NewValueName(230, "Lilith's Kiss"),
		models.NewValueName(231, "Resist Poison"),
		models.NewValueName(232, "Resist Fire"),
		models.NewValueName(233, "Dragon Shielding"),
		models.NewValueName(234, "Dark Ether"),
		models.NewValueName(235, "Dud Potion"),
		models.NewValueName(236, "Goliath Tonic"),
		models.NewValueName(237, "Antilixir"),
		models.NewValueName(238, "Phoenix Down"),
		models.NewValueName(239, "Kiss of Life"),
		models.NewValueName(240, "Lifeshield"),
		models.NewValueName(241, "Remedy"),
		models.NewValueName(242, "Resist Ice"),
		models.NewValueName(243, "Resist Thunder"),
		models.NewValueName(244, "Dragon Defense"),
		models.NewValueName(245, "Death Potion"),
		models.NewValueName(246, "Blessed Kiss"),
		models.NewValueName(247, "Succubus Kiss"),
		models.NewValueName(248, "Levisalve"),
		models.NewValueName(249, "Lamia's Kiss"),
		models.NewValueName(250, "Dragon Kiss"),
		models.NewValueName(251, "Toad Kiss"),
		models.NewValueName(252, "Holy Water"),
		models.NewValueName(253, "Bacchus's Cider"),
		models.NewValueName(254, "Samson's Might"),
		models.NewValueName(255, "Elemental Power"),
		models.NewValueName(256, "Holy Breath"),
		models.NewValueName(257, "Dud Potion"),
		models.NewValueName(258, "Protect Potion"),
		models.NewValueName(259, "Turtle Soup"),
		models.NewValueName(260, "Hasty-ade"),
		models.NewValueName(261, "Dud Potion"),
		models.NewValueName(262, "TNT"),
		models.NewValueName(263, "Antidote"),
		models.NewValueName(264, "Smelling Salts"),
		models.NewValueName(265, "Poison Breath"),
		models.NewValueName(266, "Poison"),
		models.NewValueName(267, "Eye Drop"),
		models.NewValueName(268, "Dark Sigh"),
		models.NewValueName(269, "Dark Gas"),
		models.NewValueName(270, "Dragon Breath"),
		models.NewValueName(271, "Dark Breath"),
		models.NewValueName(272, "Shadowflare"),
		models.NewValueName(273, "Mysidian Rabbit"),
		models.NewValueName(274, "Squirrel"),
		models.NewValueName(275, "Bee Swarm"),
		models.NewValueName(276, "Nightingale"),
		models.NewValueName(277, "Flying Squirrel"),
		models.NewValueName(278, "Falcon"),
		models.NewValueName(279, "Skunk"),
		models.NewValueName(280, "Wild Boar"),
		models.NewValueName(281, "Unicorn"),
		models.NewValueName(282, "Gust"),
		models.NewValueName(283, "Earthquake"),
		models.NewValueName(284, "Wind Slash"),
		models.NewValueName(285, "Twister"),
		models.NewValueName(286, "Branch Arrow"),
		models.NewValueName(287, "Leaf Swirl"),
		models.NewValueName(288, "Branch Spear"),
		models.NewValueName(289, "Bindweed"),
		models.NewValueName(290, "Sandstorm"),
		models.NewValueName(291, "Quicksand"),
		models.NewValueName(292, "Desert Storm"),
		models.NewValueName(293, "Burning Sands"),
		models.NewValueName(294, "Tsunami"),
		models.NewValueName(295, "Whirlpool"),
		models.NewValueName(296, "Big Wave"),
		models.NewValueName(298, "Phantom"),
		models.NewValueName(299, "Ignus Fatuus"),
		models.NewValueName(300, "Bottomless Bog"),
		models.NewValueName(301, "Poison Mist"),
		models.NewValueName(302, "Waterfall"),
		models.NewValueName(303, "Stalactite"),
		models.NewValueName(304, "Cave-In"),
		models.NewValueName(305, "Sonic Boom"),
		models.NewValueName(383, "Doom"),
		models.NewValueName(384, "Roulette"),
		models.NewValueName(385, "Aqua Breath"),
		models.NewValueName(386, "Level 5 Death"),
		models.NewValueName(387, "Level 4 Graviga"),
		models.NewValueName(388, "Level 2 Old"),
		models.NewValueName(389, "Level 3 Flare"),
		models.NewValueName(390, "Pond's Chorus"),
		models.NewValueName(391, "Lilliputian Lyric"),
		models.NewValueName(392, "Flash"),
		models.NewValueName(393, "Time Slip"),
		models.NewValueName(394, "Moon Flute"),
		models.NewValueName(395, "Death Claw"),
		models.NewValueName(396, "Aero"),
		models.NewValueName(397, "Aera"),
		models.NewValueName(398, "Aeroga"),
		models.NewValueName(399, "Flame Thrower"),
		models.NewValueName(400, "Goblin Punch"),
		models.NewValueName(401, "Dark Spark"),
		models.NewValueName(402, "Off-Guard"),
		models.NewValueName(403, "Transfusion"),
		models.NewValueName(404, "Mind Blast"),
		models.NewValueName(405, "Vampire"),
		models.NewValueName(406, "Magic Hammer"),
		models.NewValueName(407, "Mighty Guard"),
		models.NewValueName(408, "Self-Destruct"),
		models.NewValueName(409, "???"),
		models.NewValueName(410, "1000 Needles"),
		models.NewValueName(411, "White Wind"),
		models.NewValueName(412, "Missile"),
		models.NewValueName(413, "Ribbit"),
		models.NewValueName(415, "Flee"),
		models.NewValueName(419, "Grand Cross"),
		models.NewValueName(420, "Delta Attack"),
		models.NewValueName(421, "Interceptor"),
		models.NewValueName(424, "Wind Slash"),
		models.NewValueName(426, "Search"),
		models.NewValueName(427, "100 Gs"),
		models.NewValueName(428, "Vanish"),
		models.NewValueName(429, "Reaper's Sword"),
		models.NewValueName(430, "Punishment"),
		models.NewValueName(431, "Blaster"),
		models.NewValueName(432, "Beak"),
		models.NewValueName(433, "Embrace"),
		models.NewValueName(434, "Spore"),
		models.NewValueName(435, "Poison Breath"),
		models.NewValueName(436, "Danse Macabre"),
		models.NewValueName(437, "Zombie Powder"),
		models.NewValueName(438, "Zombie Breath"),
		models.NewValueName(439, "Paraclete"),
		models.NewValueName(440, "Entice"),
		models.NewValueName(441, "Entangle"),
		models.NewValueName(442, "Rainbow Wind"),
		models.NewValueName(443, "Dancehall Daze"),
		models.NewValueName(444, "Gamma Ray"),
		models.NewValueName(445, "White Hole"),
		models.NewValueName(446, "Needle"),
		models.NewValueName(447, "Maelstrom"),
		models.NewValueName(448, "Bone"),
		models.NewValueName(449, "Tail Screw"),
		models.NewValueName(450, "Digestive Acid"),
		models.NewValueName(451, "Rocket Punch"),
		models.NewValueName(452, "Mustard Bomb"),
		models.NewValueName(453, "Almagest"),
		models.NewValueName(454, "Quicksand"),
		models.NewValueName(455, "Atomic Ray"),
		models.NewValueName(456, "Frostbite"),
		models.NewValueName(457, "Ice Storm"),
		models.NewValueName(458, "Frost"),
		models.NewValueName(459, "Electrocute"),
		models.NewValueName(460, "Earth Shaker"),
		models.NewValueName(461, "Zantetsuken"),
		models.NewValueName(462, "Tidal Wave"),
		models.NewValueName(463, "Mega Flare"),
		models.NewValueName(464, "Dischord"),
		models.NewValueName(465, "Web"),
		models.NewValueName(466, "Slimer"),
		models.NewValueName(467, "Earthquake"),
		models.NewValueName(469, "Panacea"),
		models.NewValueName(470, "Image"),
		models.NewValueName(471, "Breath Wing"),
		models.NewValueName(472, "Blaze"),
		models.NewValueName(473, "Lightning"),
		models.NewValueName(474, "Wave Cannon"),
		models.NewValueName(478, "Giga Flare"),
		models.NewValueName(479, "Encircle"),
		models.NewValueName(480, "Wormhole"),
		models.NewValueName(481, "Possess"),
		models.NewValueName(482, "Reverse Polarity"),
		models.NewValueName(483, "Magnet"),
		models.NewValueName(485, "Jump"),
		models.NewValueName(486, "Banish"),
		models.NewValueName(487, "Hurricane"),
		models.NewValueName(488, "Demon Eye"),
		models.NewValueName(489, "Critical Attack"),
		models.NewValueName(490, "Needle"),
		models.NewValueName(491, "Incisor"),
		models.NewValueName(492, "Tail"),
		models.NewValueName(493, "Claw"),
		models.NewValueName(494, "Pincer"),
		models.NewValueName(495, "Magic Stick"),
		models.NewValueName(496, "Eight Arms"),
		models.NewValueName(497, "Ten Arms"),
		models.NewValueName(498, "Horn"),
		models.NewValueName(499, "Rush"),
		models.NewValueName(500, "Body Slam"),
		models.NewValueName(501, "Turtle"),
		models.NewValueName(502, "Dive"),
		models.NewValueName(503, "Fin"),
		models.NewValueName(504, "Feeler"),
		models.NewValueName(505, "Lick"),
		models.NewValueName(506, "Bite"),
		models.NewValueName(507, "Elbow"),
		models.NewValueName(508, "Axe"),
		models.NewValueName(509, "Headbutt"),
		models.NewValueName(510, "Right Claw"),
		models.NewValueName(511, "Tackle"),
		models.NewValueName(512, "Slap"),
		models.NewValueName(513, "Spear"),
		models.NewValueName(514, "Wing Attack"),
		models.NewValueName(515, "Thrust"),
		models.NewValueName(516, "Flying Knee"),
		models.NewValueName(517, "Spirit Blast"),
		models.NewValueName(518, "Tusk"),
		models.NewValueName(519, "Unseen Strike"),
		models.NewValueName(520, "Puncture"),
		models.NewValueName(521, "Left Jab"),
		models.NewValueName(522, "Sling"),
		models.NewValueName(523, "Toe Kick"),
		models.NewValueName(524, "Mineuchi"),
		models.NewValueName(525, "Pressure"),
		models.NewValueName(526, "Hose"),
		models.NewValueName(527, "Air Fist"),
		models.NewValueName(528, "High Kick"),
		models.NewValueName(529, "Crush"),
		models.NewValueName(530, "Knock Silly"),
		models.NewValueName(531, "Squeeze"),
		models.NewValueName(532, "Drill"),
		models.NewValueName(533, "Wring"),
		models.NewValueName(534, "Sickle"),
		models.NewValueName(535, "Yagyuu's Strike"),
		models.NewValueName(536, "Cat Scratch"),
		models.NewValueName(537, "Corner"),
		models.NewValueName(538, "Venomous Clasp"),
		models.NewValueName(539, "Takedown"),
		models.NewValueName(540, "Sap"),
		models.NewValueName(541, "Ray"),
		models.NewValueName(542, "Counter"),
		models.NewValueName(543, "Vacuum Wave"),
		models.NewValueName(544, "Knife"),
		models.NewValueName(545, "Vacuum Wave"),
		models.NewValueName(547, "Silver Powder"),
		models.NewValueName(548, "Poison Powder"),
		models.NewValueName(549, "Darkness Powder"),
		models.NewValueName(550, "Paralyze Powder"),
		models.NewValueName(551, "Confuse Powder"),
		models.NewValueName(552, "Mystery Waltz"),
		models.NewValueName(553, "Jitterbug"),
		models.NewValueName(554, "Tempting Tango"),
		models.NewValueName(556, "Sword Dance"),
		models.NewValueName(576, "Egg Chop"),
	}
)
