package ff5

import (
	"pixel-remastered-save-editor/models"
)

var (
	Bestiary = []models.NameValue{
		models.NewValueName(1, "Goblin"),
		models.NewValueName(2, "Killer Bee"),
		models.NewValueName(3, "Nutkin"),
		models.NewValueName(4, "Stray Cat"),
		models.NewValueName(5, "Steel Bat"),
		models.NewValueName(6, "Devil Crab"),
		models.NewValueName(7, "Stroper"),
		models.NewValueName(8, "Black Goblin"),
		models.NewValueName(9, "White Serpent"),
		models.NewValueName(10, "Moldwynd"),
		models.NewValueName(11, "Mani Wizard"),
		models.NewValueName(12, "Magic Pot"),
		models.NewValueName(13, "Sucker"),
		models.NewValueName(14, "Octokraken"),
		models.NewValueName(15, "Gatling"),
		models.NewValueName(16, "Big Horn"),
		models.NewValueName(17, "Tatou"),
		models.NewValueName(18, "Bandersnatch"),
		models.NewValueName(19, "Garula"),
		models.NewValueName(20, "Skeleton"),
		models.NewValueName(21, "Calcruthl"),
		models.NewValueName(22, "Undead Husk"),
		models.NewValueName(23, "Mindflusher"),
		models.NewValueName(24, "Rock Slug"),
		models.NewValueName(25, "Gaelicat"),
		models.NewValueName(26, "Cockatrice"),
		models.NewValueName(27, "Headstone"),
		models.NewValueName(28, "Elf Toad"),
		models.NewValueName(29, "Ice Soldier"),
		models.NewValueName(30, "Ricard Mage"),
		models.NewValueName(31, "Wyvern"),
		models.NewValueName(32, "Pas de Seul"),
		models.NewValueName(33, "Byblos"),
		models.NewValueName(34, "Aegir"),
		models.NewValueName(35, "Zu"),
		models.NewValueName(36, "Wild Nakk"),
		models.NewValueName(37, "Grass Tortoise"),
		models.NewValueName(38, "Silent Bee"),
		models.NewValueName(39, "Mythril Dragon"),
		models.NewValueName(40, "Ramuh"),
		models.NewValueName(41, "Crew Dust"),
		models.NewValueName(42, "Poltergeist"),
		models.NewValueName(43, "Motor Trap"),
		models.NewValueName(44, "Defeater"),
		models.NewValueName(45, "Jackanapes"),
		models.NewValueName(46, "Sergeant"),
		models.NewValueName(47, "Sorcerer"),
		models.NewValueName(48, "Cur Nakk"),
		models.NewValueName(49, "Gigas"),
		models.NewValueName(50, "Page 32"),
		models.NewValueName(51, "Page 64"),
		models.NewValueName(52, "Page 128"),
		models.NewValueName(53, "Page 256"),
		models.NewValueName(54, "Ifrit"),
		models.NewValueName(55, "Bomb"),
		models.NewValueName(56, "Doublizard"),
		models.NewValueName(57, "Bio Soldier"),
		models.NewValueName(58, "Harvester"),
		models.NewValueName(59, "Black Flame"),
		models.NewValueName(60, "Stone Golem"),
		models.NewValueName(61, "Mini Dragon"),
		models.NewValueName(62, "Prototype"),
		models.NewValueName(63, "Dhorme Chimera"),
		models.NewValueName(64, "Sandboil"),
		models.NewValueName(65, "Desert Killer"),
		models.NewValueName(66, "Sand Bear"),
		models.NewValueName(67, "Ra Mage"),
		models.NewValueName(68, "Ronkan Knight"),
		models.NewValueName(69, "Stone Mask"),
		models.NewValueName(70, "Enchanted Fan"),
		models.NewValueName(71, "Lamia"),
		models.NewValueName(72, "Archeotoad"),
		models.NewValueName(73, "Hydra"),
		models.NewValueName(74, "Ghidra"),
		models.NewValueName(75, "Devilfish"),
		models.NewValueName(76, "Treant"),
		models.NewValueName(77, "Strapparer"),
		models.NewValueName(78, "Tarantula"),
		models.NewValueName(79, "Shell Bear"),
		models.NewValueName(80, "Tunneller"),
		models.NewValueName(81, "Birostris"),
		models.NewValueName(82, "Fairy Orc"),
		models.NewValueName(83, "Devourer"),
		models.NewValueName(84, "Mandrake"),
		models.NewValueName(85, "Kuza Beast"),
		models.NewValueName(86, "Cactus"),
		models.NewValueName(87, "Sandcrawler"),
		models.NewValueName(88, "Shield Dragon"),
		models.NewValueName(89, "Blood Slime"),
		models.NewValueName(90, "Acrophies"),
		models.NewValueName(91, "Moogle Eater"),
		models.NewValueName(92, "Lesser Lopros"),
		models.NewValueName(93, "Skull Eater"),
		models.NewValueName(94, "Aquathorn"),
		models.NewValueName(95, "Weresnake"),
		models.NewValueName(96, "Kornago"),
		models.NewValueName(97, "Cursed Being"),
		models.NewValueName(98, "Undergrounder"),
		models.NewValueName(99, "Drippy"),
		models.NewValueName(100, "Lycaon"),
		models.NewValueName(101, "Bone Dragon"),
		models.NewValueName(102, "Poison Eagle"),
		models.NewValueName(103, "Zombie Dragon"),
		models.NewValueName(104, "Golem"),
		models.NewValueName(105, "Neon"),
		models.NewValueName(106, "Magnetite"),
		models.NewValueName(107, "Reflect Knight"),
		models.NewValueName(108, "Traveler"),
		models.NewValueName(109, "Level Tricker"),
		models.NewValueName(110, "Gravitator"),
		models.NewValueName(111, "Ziggurat Gigas"),
		models.NewValueName(112, "Cure Beast"),
		models.NewValueName(113, "Land Turtle"),
		models.NewValueName(114, "Dechirer"),
		models.NewValueName(115, "Catoblepas"),
		models.NewValueName(116, "Mini Magician"),
		models.NewValueName(117, "Galajelly"),
		models.NewValueName(118, "Mammon"),
		models.NewValueName(119, "Imp"),
		models.NewValueName(120, "Wyrm"),
		models.NewValueName(121, "Twin Lizard"),
		models.NewValueName(122, "Blind Wolf"),
		models.NewValueName(123, "Hellraiser"),
		models.NewValueName(124, "Reflect Mage"),
		models.NewValueName(125, "Magic Dragon"),
		models.NewValueName(126, "Black Warlock"),
		models.NewValueName(127, "Adamantite Golem"),
		models.NewValueName(128, "Bandercoeurl"),
		models.NewValueName(129, "Iron Fist"),
		models.NewValueName(130, "Blue Dragon"),
		models.NewValueName(131, "Red Dragon"),
		models.NewValueName(132, "Yellow Dragon"),
		models.NewValueName(133, "Sleepy"),
		models.NewValueName(134, "Triffid"),
		models.NewValueName(135, "Hedgehog"),
		models.NewValueName(136, "Python"),
		models.NewValueName(137, "Shadow"),
		models.NewValueName(138, "Elm Gigas"),
		models.NewValueName(139, "Pao"),
		models.NewValueName(140, "Dark Aspic"),
		models.NewValueName(141, "Metamorph"),
		models.NewValueName(142, "Unknown"),
		models.NewValueName(143, "Desertpede"),
		models.NewValueName(144, "Bulette"),
		models.NewValueName(145, "Sekhmet"),
		models.NewValueName(146, "Lamia Queen"),
		models.NewValueName(147, "Rajiformes"),
		models.NewValueName(148, "Ushabti"),
		models.NewValueName(149, "Archeosaur"),
		models.NewValueName(150, "Zephyrus"),
		models.NewValueName(151, "Exdeath's Soul"),
		models.NewValueName(152, "Slug"),
		models.NewValueName(153, "Gloom Widow"),
		models.NewValueName(154, "Mykale"),
		models.NewValueName(155, "Executor"),
		models.NewValueName(156, "Oiseaurare"),
		models.NewValueName(157, "Shadow Dancer"),
		models.NewValueName(158, "The Damned"),
		models.NewValueName(159, "Numb Blade"),
		models.NewValueName(160, "Tiny Mage"),
		models.NewValueName(161, "Chrono Controller"),
		models.NewValueName(162, "Bone Dragon"),
		models.NewValueName(163, "Flaremancer"),
		models.NewValueName(164, "Dueling Knight"),
		models.NewValueName(165, "Iron Muscles"),
		models.NewValueName(166, "Berserker"),
		models.NewValueName(167, "Zombie Dragon"),
		models.NewValueName(168, "Druid"),
		models.NewValueName(169, "Ironback"),
		models.NewValueName(170, "Objet d'Art"),
		models.NewValueName(171, "Frost Bull"),
		models.NewValueName(172, "Istory Lythos"),
		models.NewValueName(173, "Spizzner"),
		models.NewValueName(174, "Unknown"),
		models.NewValueName(175, "Unknown"),
		models.NewValueName(176, "Unknown"),
		models.NewValueName(177, "Unknown"),
		models.NewValueName(178, "Mercury Bat"),
		models.NewValueName(179, "Coral"),
		models.NewValueName(180, "Tonberry"),
		models.NewValueName(181, "Aquagel"),
		models.NewValueName(182, "Steel Fist"),
		models.NewValueName(183, "Alchymia"),
		models.NewValueName(187, "Grenade"),
		models.NewValueName(188, "Sword Dancer"),
		models.NewValueName(189, "Baldanders"),
		models.NewValueName(190, "Death Dealer"),
		models.NewValueName(191, "Ankheg"),
		models.NewValueName(192, "Ammonite"),
		models.NewValueName(193, "Landcrawler"),
		models.NewValueName(194, "Lemure"),
		models.NewValueName(195, "Parthenope"),
		models.NewValueName(196, "Cherie"),
		models.NewValueName(197, "White Flame"),
		models.NewValueName(198, "Moss Fungus"),
		models.NewValueName(199, "Orukat"),
		models.NewValueName(200, "Iron Giant"),
		models.NewValueName(201, "Death Claw"),
		models.NewValueName(202, "King Behemoth"),
		models.NewValueName(203, "Farfarello"),
		models.NewValueName(204, "Necromancer"),
		models.NewValueName(205, "Ninja"),
		models.NewValueName(206, "Great Dragon"),
		models.NewValueName(207, "Dragon Aevis"),
		models.NewValueName(208, "Gorgimera"),
		models.NewValueName(209, "Level Checker"),
		models.NewValueName(210, "Mindflayer"),
		models.NewValueName(211, "Fury"),
		models.NewValueName(212, "Crystelle"),
		models.NewValueName(213, "Mover"),
		models.NewValueName(214, "Crystal Dragon"),
		models.NewValueName(215, "Achelon"),
		models.NewValueName(216, "Yojimbo"),
		models.NewValueName(217, "Gilgamesh"),
		models.NewValueName(218, "Sahagin"),
		models.NewValueName(219, "Thunder Anemone"),
		models.NewValueName(220, "Sea Ibis"),
		models.NewValueName(221, "Corbett"),
		models.NewValueName(222, "Nix"),
		models.NewValueName(223, "Water Scorpion"),
		models.NewValueName(224, "Vilia"),
		models.NewValueName(225, "Gel Fish"),
		models.NewValueName(226, "Rukh"),
		models.NewValueName(227, "Sea Devil"),
		models.NewValueName(228, "Stingray"),
		models.NewValueName(230, "Golem"),
		models.NewValueName(232, "Shiva"),
		models.NewValueName(233, "Ifrit"),
		models.NewValueName(234, "Ramuh"),
		models.NewValueName(235, "Gaelicat"),
		models.NewValueName(236, "Wyvern"),
		models.NewValueName(237, "Elf Toad"),
		models.NewValueName(238, "Crew Dust"),
		models.NewValueName(239, "Enchanted Fan"),
		models.NewValueName(240, "Zombie Dragon"),
		models.NewValueName(241, "Dhorme Chimera"),
		models.NewValueName(242, "Adamantite Golem"),
		models.NewValueName(243, "Ziggurat Gigas"),
		models.NewValueName(244, "Ronkan Knight"),
		models.NewValueName(245, "Bio Soldier"),
		models.NewValueName(246, "Tunneller"),
		models.NewValueName(247, "Tot Aevis"),
		models.NewValueName(248, "Belphegor"),
		models.NewValueName(249, "Imp"),
		models.NewValueName(250, "Oiseaurare"),
		models.NewValueName(251, "Jackanapes"),
		models.NewValueName(252, "Gobbledygook"),
		models.NewValueName(253, "Gil Turtle"),
		models.NewValueName(254, "Omega"),
		models.NewValueName(280, "Mecha Head"),
		models.NewValueName(281, "Wing Raptor"),
		models.NewValueName(282, "Wing Raptor"),
		models.NewValueName(283, "Karlabos"),
		models.NewValueName(284, "Twintania"),
		models.NewValueName(285, "Siren"),
		models.NewValueName(286, "Siren"),
		models.NewValueName(287, "Forza"),
		models.NewValueName(288, "Magissa"),
		models.NewValueName(289, "Garula"),
		models.NewValueName(290, "Liquid Flame"),
		models.NewValueName(291, "Liquid Flame"),
		models.NewValueName(292, "Liquid Flame"),
		models.NewValueName(293, "Ice Commander"),
		models.NewValueName(294, "Sandworm"),
		models.NewValueName(295, "Hole"),
		models.NewValueName(296, "Adamantoise"),
		models.NewValueName(297, "Flame Thrower"),
		models.NewValueName(298, "Rocket Launcher"),
		models.NewValueName(299, "Exdeath"),
		models.NewValueName(300, "Soul Cannon"),
		models.NewValueName(301, "Archeoaevis"),
		models.NewValueName(302, "Archeoaevis"),
		models.NewValueName(303, "Archeoaevis"),
		models.NewValueName(304, "Archeoaevis"),
		models.NewValueName(305, "Archeoaevis"),
		models.NewValueName(306, "Chimera Brain"),
		models.NewValueName(307, "Titan"),
		models.NewValueName(308, "Purobolos"),
		models.NewValueName(309, "Abductor"),
		models.NewValueName(310, "Gilgamesh"),
		models.NewValueName(311, "Merrow"),
		models.NewValueName(312, "Flying Killer"),
		models.NewValueName(313, "Little Chariot"),
		models.NewValueName(314, "Neo Garula"),
		models.NewValueName(315, "Gilgamesh"),
		models.NewValueName(316, "Tyrannosaur"),
		models.NewValueName(317, "Shiva"),
		models.NewValueName(318, "Abductor"),
		models.NewValueName(319, "Dragon Pod"),
		models.NewValueName(320, "Dragon Flower"),
		models.NewValueName(321, "Dragon Flower"),
		models.NewValueName(322, "Dragon Flower"),
		models.NewValueName(323, "Dragon Flower"),
		models.NewValueName(324, "Dragon Flower"),
		models.NewValueName(325, "Gilgamesh"),
		models.NewValueName(326, "Enkidu"),
		models.NewValueName(327, "Atomos"),
		models.NewValueName(332, "Carbuncle"),
		models.NewValueName(334, "Gilgamesh"),
		models.NewValueName(335, "Exdeath"),
		models.NewValueName(336, "Antlion"),
		models.NewValueName(337, "Mummy"),
		models.NewValueName(338, "Aspis"),
		models.NewValueName(339, "Mecha Head"),
		models.NewValueName(340, "Melusine"),
		models.NewValueName(341, "Melusine"),
		models.NewValueName(342, "Melusine"),
		models.NewValueName(343, "Melusine"),
		models.NewValueName(344, "Odin"),
		models.NewValueName(345, "Gargoyle"),
		models.NewValueName(346, "Triton"),
		models.NewValueName(347, "Nereid"),
		models.NewValueName(348, "Phobos"),
		models.NewValueName(349, "Omniscient"),
		models.NewValueName(350, "Minotaur"),
		models.NewValueName(351, "Leviathan"),
		models.NewValueName(352, "Wendigo"),
		models.NewValueName(353, "Famed Mimic Gogo"),
		models.NewValueName(354, "Bahamut"),
		models.NewValueName(355, "Jura Aevis"),
		models.NewValueName(356, "Halicarnassus"),
		models.NewValueName(357, "Exdeath"),
		models.NewValueName(358, "Neo Exdeath"),
		models.NewValueName(359, "Neo Exdeath"),
		models.NewValueName(360, "Goblin"),
		models.NewValueName(361, "Iron Claw"),
		models.NewValueName(362, "Sergeant"),
		models.NewValueName(363, "Cur Nakk"),
		models.NewValueName(364, "Cray Claw"),
		models.NewValueName(366, "Calofisteri"),
		models.NewValueName(367, "Azulmagia"),
		models.NewValueName(368, "Catastrophe"),
		models.NewValueName(369, "Necrophobe"),
		models.NewValueName(370, "Twintania"),
		models.NewValueName(371, "Launcher"),
		models.NewValueName(372, "Launcher"),
		models.NewValueName(373, "Gilgamesh"),
		models.NewValueName(374, "Carbuncle"),
		models.NewValueName(375, "Grand Mummy"),
		models.NewValueName(376, "Apanda"),
		models.NewValueName(377, "Alte Roite"),
		models.NewValueName(378, "Covert"),
		models.NewValueName(379, "Abductor"),
		models.NewValueName(380, "Bandercoeurl"),
		models.NewValueName(381, "Liquid Flame"),
		models.NewValueName(382, "Kuza Beast"),
		models.NewValueName(383, "Soul Cannon"),
		models.NewValueName(384, "Pantera"),
		models.NewValueName(385, "Shinryu"),
		models.NewValueName(386, "Barrier"),
		models.NewValueName(387, "Neo Exdeath"),
		models.NewValueName(388, "Neo Exdeath"),
		models.NewValueName(389, "Neo Exdeath"),
		models.NewValueName(390, "Neo Exdeath"),
		models.NewValueName(391, "Gilgamesh"),
		models.NewValueName(472, "Metamorph"),
		models.NewValueName(473, "Metamorph"),
		models.NewValueName(474, "Metamorph"),
		models.NewValueName(475, "Zephyrus"),
		models.NewValueName(476, "Zephyrus"),
		models.NewValueName(477, "Necrophobe"),
		models.NewValueName(478, "Mover"),
		models.NewValueName(481, "Tonberry"),
		models.NewValueName(482, "Tonberry"),
		models.NewValueName(483, "Tonberry"),
		models.NewValueName(484, "Tonberry"),
		models.NewValueName(485, "Tonberry"),
		models.NewValueName(486, "Red Dragon"),
		models.NewValueName(487, "Ghidra"),
		models.NewValueName(488, "Necrophobe"),
		models.NewValueName(489, "Necrophobe"),
		models.NewValueName(510, "Covert"),
		models.NewValueName(511, "Neo Exdeath"),
		models.NewValueName(513, "Antlion"),
		models.NewValueName(514, "Exdeath"),
		models.NewValueName(515, "Byblos"),
		models.NewValueName(516, "Gilgamesh"),
		models.NewValueName(517, "Melusine"),
	}
)
