package ff3

import (
	"pixel-remastered-save-editor/models"
)

var (
	Bestiary = []models.NameValue{
		models.NewValueName(1, "Goblin"),
		models.NewValueName(2, "Carbuncle"),
		models.NewValueName(3, "Eye Fang"),
		models.NewValueName(4, "Blue Wisp"),
		models.NewValueName(5, "Killer Bee"),
		models.NewValueName(6, "Werewolf"),
		models.NewValueName(7, "Berserker"),
		models.NewValueName(8, "Red Wisp"),
		models.NewValueName(9, "Dark Eye"),
		models.NewValueName(10, "Zombie"),
		models.NewValueName(11, "Mummy"),
		models.NewValueName(12, "Skeleton"),
		models.NewValueName(13, "Cursed Copper"),
		models.NewValueName(14, "Larva"),
		models.NewValueName(15, "Shadow"),
		models.NewValueName(16, "Revenant"),
		models.NewValueName(17, "Firefly"),
		models.NewValueName(18, "Helldiver"),
		models.NewValueName(19, "Rust Bird"),
		models.NewValueName(20, "Rukh"),
		models.NewValueName(21, "Basilisk"),
		models.NewValueName(22, "Bugbear"),
		models.NewValueName(23, "Mandrake"),
		models.NewValueName(24, "Leprechaun"),
		models.NewValueName(25, "Demonface"),
		models.NewValueName(26, "Petit"),
		models.NewValueName(27, "Poison Bat"),
		models.NewValueName(28, "Lilliputian"),
		models.NewValueName(29, "Wererat"),
		models.NewValueName(30, "Blood Worm"),
		models.NewValueName(31, "Killer Fish"),
		models.NewValueName(32, "Hermit"),
		models.NewValueName(33, "Sea Elemental"),
		models.NewValueName(34, "Tangie"),
		models.NewValueName(35, "Sahagin"),
		models.NewValueName(36, "Parademon"),
		models.NewValueName(37, "Griffon"),
		models.NewValueName(38, "Lynx"),
		models.NewValueName(39, "Hornet"),
		models.NewValueName(40, "Knocker"),
		models.NewValueName(41, "Flyer"),
		models.NewValueName(42, "Lizardman"),
		models.NewValueName(43, "Gorgon"),
		models.NewValueName(44, "Red Cap"),
		models.NewValueName(45, "Barometz"),
		models.NewValueName(46, "Slime"),
		models.NewValueName(47, "Tarantula"),
		models.NewValueName(48, "Cuphgel"),
		models.NewValueName(49, "Pugman"),
		models.NewValueName(50, "Far Darrig"),
		models.NewValueName(51, "Blood Bat"),
		models.NewValueName(52, "Petit Mage"),
		models.NewValueName(53, "Fury"),
		models.NewValueName(54, "Aughisky"),
		models.NewValueName(55, "Bomb"),
		models.NewValueName(56, "Manticore"),
		models.NewValueName(57, "Stalagmite"),
		models.NewValueName(58, "Sea Devil"),
		models.NewValueName(59, "Merman"),
		models.NewValueName(60, "Ruinous Wave"),
		models.NewValueName(61, "Balloon"),
		models.NewValueName(62, "Myrmecoleon"),
		models.NewValueName(63, "Crocotta"),
		models.NewValueName(64, "Adamantoise"),
		models.NewValueName(65, "Red Marshmallow"),
		models.NewValueName(66, "Pharaoh"),
		models.NewValueName(67, "Lemur"),
		models.NewValueName(68, "Lamia"),
		models.NewValueName(69, "Demon"),
		models.NewValueName(70, "Dullahan"),
		models.NewValueName(71, "Anet"),
		models.NewValueName(72, "Mermaid"),
		models.NewValueName(73, "Seahorse"),
		models.NewValueName(74, "Sea Serpent"),
		models.NewValueName(75, "Cockatrice"),
		models.NewValueName(76, "Poison Toad"),
		models.NewValueName(77, "Twin Heads"),
		models.NewValueName(78, "Roper"),
		models.NewValueName(79, "Agaliarept"),
		models.NewValueName(80, "Darklegs"),
		models.NewValueName(81, "Gigantoad"),
		models.NewValueName(82, "Twin Liger"),
		models.NewValueName(83, "Stroper"),
		models.NewValueName(84, "Black Flan"),
		models.NewValueName(85, "Hellgaroo"),
		models.NewValueName(86, "Vulcan"),
		models.NewValueName(87, "Dracrocotta"),
		models.NewValueName(88, "Magician"),
		models.NewValueName(89, "Lost Gold"),
		models.NewValueName(90, "Gold Eagle"),
		models.NewValueName(91, "Gold Warrior"),
		models.NewValueName(92, "Gold Bear"),
		models.NewValueName(93, "Gold Knight"),
		models.NewValueName(94, "Nightmare"),
		models.NewValueName(95, "Hellgaroo Mage"),
		models.NewValueName(96, "Needle Monkey"),
		models.NewValueName(97, "Catoblepas"),
		models.NewValueName(98, "Sorceror"),
		models.NewValueName(99, "Sand Worm"),
		models.NewValueName(100, "Frostfly"),
		models.NewValueName(101, "Simurgh"),
		models.NewValueName(102, "Harpy"),
		models.NewValueName(103, "Gargoyle"),
		models.NewValueName(104, "Chimera"),
		models.NewValueName(105, "Demon Horse"),
		models.NewValueName(106, "Rock Gargoyle"),
		models.NewValueName(107, "Bovian"),
		models.NewValueName(108, "Dread Knight"),
		models.NewValueName(109, "Flyer Mage"),
		models.NewValueName(110, "Noggle"),
		models.NewValueName(111, "Abtu"),
		models.NewValueName(112, "Sea Dragon"),
		models.NewValueName(113, "Kagura"),
		models.NewValueName(114, "Charybdis"),
		models.NewValueName(115, "Dozmare"),
		models.NewValueName(116, "Sea Witch"),
		models.NewValueName(117, "Killer Hermit"),
		models.NewValueName(118, "Ologhai"),
		models.NewValueName(119, "Kelpie"),
		models.NewValueName(120, "Aegir"),
		models.NewValueName(121, "Kyklops"),
		models.NewValueName(122, "Boss Troll"),
		models.NewValueName(123, "Fachan"),
		models.NewValueName(124, "Cenchos"),
		models.NewValueName(125, "Balor"),
		models.NewValueName(126, "Dira"),
		models.NewValueName(127, "Chimera Mage"),
		models.NewValueName(128, "King Lizard"),
		models.NewValueName(129, "Pterodactyl"),
		models.NewValueName(130, "Wyvern"),
		models.NewValueName(131, "Behemoth"),
		models.NewValueName(132, "King Seahorse"),
		models.NewValueName(133, "Dragon"),
		models.NewValueName(134, "Pyralis"),
		models.NewValueName(135, "Silenus"),
		models.NewValueName(136, "Gaap"),
		models.NewValueName(137, "Azrael"),
		models.NewValueName(138, "Eater"),
		models.NewValueName(139, "Ouroboros"),
		models.NewValueName(140, "Plancti"),
		models.NewValueName(141, "Sea Lion"),
		models.NewValueName(142, "Remora"),
		models.NewValueName(143, "Grenade"),
		models.NewValueName(144, "Drake"),
		models.NewValueName(145, "Greater Boros"),
		models.NewValueName(146, "Sabertooth Liger"),
		models.NewValueName(147, "Queen Lamia"),
		models.NewValueName(148, "Zombie Dragon"),
		models.NewValueName(149, "Death Claw"),
		models.NewValueName(150, "Hellish Horse"),
		models.NewValueName(151, "Chronos"),
		models.NewValueName(152, "Valefor"),
		models.NewValueName(153, "Haniel"),
		models.NewValueName(154, "Vassago"),
		models.NewValueName(155, "Peryton"),
		models.NewValueName(156, "Ogre"),
		models.NewValueName(157, "Cyclops"),
		models.NewValueName(158, "Nemesis"),
		models.NewValueName(159, "Humbaba"),
		models.NewValueName(160, "Death Needle"),
		models.NewValueName(161, "Liger"),
		models.NewValueName(162, "Aeon"),
		models.NewValueName(163, "Minotaur"),
		models.NewValueName(164, "Iron Claws"),
		models.NewValueName(165, "Greater Demon"),
		models.NewValueName(166, "Unei's Clone"),
		models.NewValueName(167, "Thanatos"),
		models.NewValueName(168, "Bone Dragon"),
		models.NewValueName(169, "King Behemoth"),
		models.NewValueName(170, "Abaia"),
		models.NewValueName(171, "Sleipnir"),
		models.NewValueName(172, "Haokah"),
		models.NewValueName(173, "Acheron"),
		models.NewValueName(174, "Oceanus"),
		models.NewValueName(175, "Gomory"),
		models.NewValueName(176, "Bluck"),
		models.NewValueName(177, "Doga's Clone"),
		models.NewValueName(178, "Azer"),
		models.NewValueName(179, "Platinal"),
		models.NewValueName(180, "Qumqum"),
		models.NewValueName(181, "Shinobi"),
		models.NewValueName(182, "Shadow Master"),
		models.NewValueName(183, "Kage"),
		models.NewValueName(184, "Dark General"),
		models.NewValueName(185, "Yellow Dragon"),
		models.NewValueName(186, "Green Dragon"),
		models.NewValueName(187, "Red Dragon"),
		models.NewValueName(188, "Glasya Labolas"),
		models.NewValueName(189, "Yormungand"),
		models.NewValueName(190, "Thor"),
		models.NewValueName(191, "Hecatoncheir"),
		models.NewValueName(192, "Hydra"),
		models.NewValueName(193, "Queen Scylla"),
		models.NewValueName(194, "Garm"),
		models.NewValueName(195, "Twin Dragon"),
		models.NewValueName(196, "Land Turtle"),
		models.NewValueName(197, "Djinn"),
		models.NewValueName(198, "Nepto Dragon"),
		models.NewValueName(199, "Giant Rat"),
		models.NewValueName(200, "Medusa"),
		models.NewValueName(201, "Gutsco"),
		models.NewValueName(202, "Salamander"),
		models.NewValueName(203, "Hein"),
		models.NewValueName(204, "Kraken"),
		models.NewValueName(205, "Goldor"),
		models.NewValueName(206, "Garuda"),
		models.NewValueName(207, "Odin"),
		models.NewValueName(208, "Leviathan"),
		models.NewValueName(209, "Bahamut"),
		models.NewValueName(210, "Doga"),
		models.NewValueName(211, "Unei"),
		models.NewValueName(212, "Titan"),
		models.NewValueName(213, "Ninja"),
		models.NewValueName(214, "Amon"),
		models.NewValueName(215, "Kunoichi"),
		models.NewValueName(216, "General"),
		models.NewValueName(217, "Guardian"),
		models.NewValueName(218, "Scylla"),
		models.NewValueName(219, "Xande"),
		models.NewValueName(220, "Xande's Clone"),
		models.NewValueName(221, "Cerberus"),
		models.NewValueName(222, "Two-Headed Dragon"),
		models.NewValueName(223, "Echidna"),
		models.NewValueName(224, "Ahriman"),
		models.NewValueName(225, "Cloud of Darkness"),
		models.NewValueName(226, "Cloud of Darkness (unwinnable version)"),
		models.NewValueName(227, "Bahamut (unwinnable version)"),
		models.NewValueName(228, "Silenus"),
		models.NewValueName(229, "Gaap"),
		models.NewValueName(230, "Azrael"),
		models.NewValueName(231, "Eater"),
		models.NewValueName(232, "Chronos"),
		models.NewValueName(233, "Valefor"),
		models.NewValueName(234, "Haniel"),
		models.NewValueName(235, "Vassago"),
		models.NewValueName(236, "Iron Claws"),
		models.NewValueName(237, "Qumqum"),
		models.NewValueName(238, "Shinobi"),
	}
)
