package ff2

import (
	"pixel-remastered-save-editor/models"
)

var (
	Bestiary = []models.NameValue{
		models.NewValueName(1, "Leg Eater"),
		models.NewValueName(2, "Vampire Thorn"),
		models.NewValueName(3, "Hornet"),
		models.NewValueName(4, "Queen Bee"),
		models.NewValueName(5, "Snowman"),
		models.NewValueName(6, "Sasquatch"),
		models.NewValueName(7, "Icicle"),
		models.NewValueName(8, "Stalactite"),
		models.NewValueName(9, "Stalagmite"),
		models.NewValueName(10, "Sprinter"),
		models.NewValueName(11, "Phorusracos"),
		models.NewValueName(12, "Adamantoise"),
		models.NewValueName(13, "Land Turtle"),
		models.NewValueName(14, "Ogre"),
		models.NewValueName(15, "Ogre Mage"),
		models.NewValueName(16, "Ogre Chief"),
		models.NewValueName(17, "Dual Heads"),
		models.NewValueName(18, "Dual Deads"),
		models.NewValueName(19, "Wererat"),
		models.NewValueName(20, "Stunner"),
		models.NewValueName(21, "Dead Head"),
		models.NewValueName(22, "Skull"),
		models.NewValueName(23, "Zombie"),
		models.NewValueName(24, "Ghoul"),
		models.NewValueName(25, "Ghast"),
		models.NewValueName(26, "Revenant"),
		models.NewValueName(27, "Shadow"),
		models.NewValueName(28, "Wraith"),
		models.NewValueName(29, "Specter"),
		models.NewValueName(30, "Ghost"),
		models.NewValueName(31, "Antlion"),
		models.NewValueName(32, "Scissorjaws"),
		models.NewValueName(33, "Gottos"),
		models.NewValueName(34, "Beast Demon"),
		models.NewValueName(35, "Chimera"),
		models.NewValueName(36, "Rhyos"),
		models.NewValueName(37, "Chimera Sphinx"),
		models.NewValueName(38, "Death Flower"),
		models.NewValueName(39, "Devil's Bloom"),
		models.NewValueName(40, "Killer Fish"),
		models.NewValueName(41, "Bolt Fish"),
		models.NewValueName(42, "Helldiver"),
		models.NewValueName(43, "Cockatrice"),
		models.NewValueName(44, "Pirate"),
		models.NewValueName(45, "Buccaneer"),
		models.NewValueName(46, "Borghen"),
		models.NewValueName(47, "Zombie Borghen"),
		models.NewValueName(48, "Big Horn"),
		models.NewValueName(49, "Wild Horn"),
		models.NewValueName(50, "Poison Toad"),
		models.NewValueName(51, "Gigantoad"),
		models.NewValueName(52, "Sea Snake"),
		models.NewValueName(53, "Sea Dragon"),
		models.NewValueName(54, "Land Ray"),
		models.NewValueName(55, "Manta Ray"),
		models.NewValueName(56, "Flying Ray"),
		models.NewValueName(57, "Changer"),
		models.NewValueName(58, "Brain"),
		models.NewValueName(59, "Parasite"),
		models.NewValueName(60, "Mega Parasite"),
		models.NewValueName(61, "Werewolf"),
		models.NewValueName(62, "Devil Wolf"),
		models.NewValueName(63, "Imp"),
		models.NewValueName(64, "Pit Fiend"),
		models.NewValueName(65, "Malboro"),
		models.NewValueName(66, "Malboro Terra"),
		models.NewValueName(67, "Great Malboro"),
		models.NewValueName(68, "Basilisk"),
		models.NewValueName(69, "Salamander"),
		models.NewValueName(70, "Ice Lizard"),
		models.NewValueName(71, "Eyemoeba"),
		models.NewValueName(72, "Hecteyes"),
		models.NewValueName(73, "Roundworm"),
		models.NewValueName(74, "Sand Worm"),
		models.NewValueName(75, "Abyss Worm"),
		models.NewValueName(76, "Green Slime"),
		models.NewValueName(77, "Yellow Jelly"),
		models.NewValueName(78, "Red Mousse"),
		models.NewValueName(79, "Black Flan"),
		models.NewValueName(80, "Red Soul"),
		models.NewValueName(81, "Green Soul"),
		models.NewValueName(82, "Yellow Soul"),
		models.NewValueName(83, "Vampire Girl"),
		models.NewValueName(84, "Vampire Lady"),
		models.NewValueName(85, "Emperor"),
		models.NewValueName(86, "Imperial Shadow"),
		models.NewValueName(87, "Killer Mantis"),
		models.NewValueName(88, "Mantis King"),
		models.NewValueName(89, "Mantis Devil"),
		models.NewValueName(90, "Royal Guard"),
		models.NewValueName(91, "Black Knight"),
		models.NewValueName(92, "Death Rider"),
		models.NewValueName(93, "Wood Golem"),
		models.NewValueName(94, "Stone Golem"),
		models.NewValueName(95, "Mythril Golem"),
		models.NewValueName(96, "Goblin"),
		models.NewValueName(97, "Goblin Guard"),
		models.NewValueName(98, "Goblin Prince"),
		models.NewValueName(99, "Balloon"),
		models.NewValueName(100, "Grenade"),
		models.NewValueName(101, "Mine"),
		models.NewValueName(102, "Bomb"),
		models.NewValueName(103, "Soldier"),
		models.NewValueName(104, "Sergeant"),
		models.NewValueName(105, "Captain"),
		models.NewValueName(106, "General"),
		models.NewValueName(107, "Magician"),
		models.NewValueName(108, "Sorcerer"),
		models.NewValueName(109, "Wizard"),
		models.NewValueName(110, "Werepanther"),
		models.NewValueName(111, "Coeurl"),
		models.NewValueName(112, "Lamia"),
		models.NewValueName(113, "Lamia Queen"),
		models.NewValueName(114, "Hill Gigas"),
		models.NewValueName(115, "Fire Gigas"),
		models.NewValueName(116, "Ice Gigas"),
		models.NewValueName(117, "Thunder Gigas"),
		models.NewValueName(118, "Behemoth"),
		models.NewValueName(119, "King Behemoth"),
		models.NewValueName(120, "White Dragon"),
		models.NewValueName(121, "Green Dragon"),
		models.NewValueName(122, "Blue Dragon"),
		models.NewValueName(123, "Red Dragon"),
		models.NewValueName(124, "Iron Giant"),
		models.NewValueName(125, "Tiamat"),
		models.NewValueName(126, "Beelzebub"),
		models.NewValueName(127, "Astaroth"),
		models.NewValueName(128, "Emperor"),
		models.NewValueName(129, "Sergeant"),
		models.NewValueName(130, "Adamantoise"),
		models.NewValueName(131, "Borghen"),
		models.NewValueName(132, "Red Soul"),
		models.NewValueName(133, "Captain"),
		models.NewValueName(134, "Chimera"),
		models.NewValueName(135, "Lamia Queen"),
		models.NewValueName(136, "Behemoth"),
		models.NewValueName(137, "Gottos"),
		models.NewValueName(138, "Big Horn"),
		models.NewValueName(139, "Roundworm"),
		models.NewValueName(140, "Fire Gigas"),
		models.NewValueName(141, "Ice Gigas"),
		models.NewValueName(142, "Thunder Gigas"),
	}
)
